-- =========================================================================
-- Pulse seed data — auto-generated by scripts/generate-seed-sql.mjs
-- Run AFTER applying supabase/schema.sql. Idempotent (ON CONFLICT).
-- =========================================================================

BEGIN;

-- [local] Massive potholes on Main St near 9th Ave
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-1',
  'statement',
  'local',
  'Massive potholes on Main St near 9th Ave',
  'Three huge potholes have been here for months. Multiple cars have been damaged. This needs immediate attention.',
  'pothole',
  'Main St & 9th Ave',
  44.025, -88.544,
  false,
  234,
  '[{"type":"image","preview":"/demo-photos/pothole-1.jpg"},{"type":"image","preview":"/demo-photos/pothole-2.jpg"}]'::jsonb,
  NULL,
  'Marcus T.',
  NOW() - INTERVAL '5 days 22 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-1-c1', p.id, 'I hit one of these last week and it bent my rim. $400 repair.', false,
  0, 'OshkoshNative', NOW() - INTERVAL '10 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-1'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-1-c2', p.id, 'The school bus route goes right through here too.', false,
  0, 'CommuteDad', NOW() - INTERVAL '23 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-1'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Streetlights out on Algoma Blvd for 3 weeks
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-2',
  'statement',
  'local',
  'Streetlights out on Algoma Blvd for 3 weeks',
  'The entire block between Jackson and Division has no streetlights. Safety hazard at night.',
  'safety',
  'Algoma Blvd',
  44.022, -88.55,
  true,
  168,
  '[{"type":"image","preview":"/demo-photos/streetlights-1.jpg"}]'::jsonb,
  NULL,
  NULL,
  NOW() - INTERVAL '1 days 8 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] New mural downtown looks incredible
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-3',
  'statement',
  'local',
  'New mural downtown looks incredible',
  'Shoutout to whoever organized the mural project on Oregon St. More of this please!',
  'compliment',
  'Oregon St',
  44.024, -88.541,
  false,
  174,
  '[{"type":"image","preview":"/demo-photos/mural-1.jpg"},{"type":"image","preview":"/demo-photos/mural-2.jpg"}]'::jsonb,
  NULL,
  'Jamie L.',
  NOW() - INTERVAL '6 days 2 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-3-c3', p.id, 'The artist is from Milwaukee! They did an amazing job.', false,
  0, 'ArtLover', NOW() - INTERVAL '7 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-3'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Construction noise at 6am every Saturday
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-4',
  'statement',
  'local',
  'Construction noise at 6am every Saturday',
  'The new development on Jackson St starts heavy machinery at 6am on weekends. City ordinance says 8am.',
  'noise',
  'Jackson St',
  44.028, -88.538,
  true,
  87,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL '3 days 7 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] South Park playground equipment is broken
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-5',
  'statement',
  'local',
  'South Park playground equipment is broken',
  'Two swings are broken and the slide has a crack. Kids are still playing on it — someone could get hurt.',
  'parks',
  'South Park',
  44.02, -88.548,
  false,
  128,
  '[{"type":"image","preview":"/demo-photos/playground-1.jpg"},{"type":"image","preview":"/demo-photos/playground-2.jpg"},{"type":"image","preview":"/demo-photos/playground-3.jpg"}]'::jsonb,
  NULL,
  'Desiree W.',
  NOW() - INTERVAL '1 days 18 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] Route 21 bus always 10+ minutes late
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-6',
  'statement',
  'local',
  'Route 21 bus always 10+ minutes late',
  'I rely on public transit to get to work. The Route 21 bus has been consistently late for the past month. This affects dozens of riders daily.',
  'transit',
  'Route 21 — Murdock Ave',
  44.019, -88.535,
  false,
  119,
  NULL,
  NULL,
  'DeShawn R.',
  NOW() - INTERVAL '6 days 12 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-6-c4', p.id, 'Same here. I''ve been late to work 3 times this month because of this.', false,
  0, 'BusRider22', NOW() - INTERVAL '33 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-6'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Shout out to the new downtown farmers market
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-7',
  'statement',
  'local',
  'Shout out to the new downtown farmers market',
  'Great variety, friendly vendors, and it brings the community together every Saturday. Love seeing Oshkosh thrive like this.',
  'compliment',
  'Downtown Oshkosh',
  44.024, -88.543,
  false,
  89,
  '[{"type":"image","preview":"/demo-photos/farmers-market-1.jpg"},{"type":"image","preview":"/demo-photos/farmers-market-2.jpg"},{"type":"image","preview":"/demo-photos/farmers-market-3.jpg"},{"type":"image","preview":"/demo-photos/farmers-market-4.jpg"}]'::jsonb,
  NULL,
  'Natalie K.',
  NOW() - INTERVAL '0 days 14 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] Affordable housing near campus is disappearing
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-8',
  'statement',
  'local',
  'Affordable housing near campus is disappearing',
  'Every apartment near UWO is being converted to luxury units. Students and low-income families are being priced out.',
  'housing',
  'Near UW Oshkosh',
  44.027, -88.553,
  true,
  187,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL '5 days 20 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] Crosswalk on Witzel Ave is barely visible
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-9',
  'statement',
  'local',
  'Crosswalk on Witzel Ave is barely visible',
  'The paint has completely faded. Cars blow through it constantly. Someone is going to get hit.',
  'safety',
  'Witzel Ave & Westfield',
  44.021, -88.556,
  false,
  142,
  NULL,
  NULL,
  'Desiree W.',
  NOW() - INTERVAL '2 days 20 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-9-c9a', p.id, 'My kids cross here every day for school. Terrifying.', false,
  0, 'CommuteDad', NOW() - INTERVAL '13 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-9'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Thank you Oshkosh PD for the community cookout
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-10',
  'statement',
  'local',
  'Thank you Oshkosh PD for the community cookout',
  'Officers grilling burgers and playing basketball with neighborhood kids. This is what community policing looks like.',
  'compliment',
  'Menominee Park',
  44.019, -88.532,
  false,
  72,
  NULL,
  NULL,
  'Marcus T.',
  NOW() - INTERVAL '4 days 15 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-10-c10a', p.id, 'This is the Oshkosh I grew up in. More of this please.', false,
  0, 'OshkoshNative', NOW() - INTERVAL '23 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-10'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Sinkhole forming on Ohio St near the bridge
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-11',
  'statement',
  'local',
  'Sinkhole forming on Ohio St near the bridge',
  'The road is literally caving in. You can see the ground shifting. This is a disaster waiting to happen.',
  'pothole',
  'Ohio St Bridge',
  44.023, -88.539,
  false,
  256,
  NULL,
  NULL,
  'DeShawn R.',
  NOW() - INTERVAL '6 days 16 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] Bar noise on Oregon St until 3am every weekend
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-12',
  'statement',
  'local',
  'Bar noise on Oregon St until 3am every weekend',
  'Bass-heavy music shaking our windows. We have a 6-month-old baby. The noise ordinance clearly isn''t enforced.',
  'noise',
  'Oregon St',
  44.024, -88.542,
  true,
  96,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL '5 days 20 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-12-c12a', p.id, 'I love Oregon St but the late night noise is getting out of control.', false,
  0, 'ArtLover', NOW() - INTERVAL '30 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-12'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] New bike lanes on Jackson St are amazing
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-13',
  'statement',
  'local',
  'New bike lanes on Jackson St are amazing',
  'Finally feel safe biking to work. Protected lanes, clear markings, and drivers are actually respecting them.',
  'compliment',
  'Jackson St',
  44.026, -88.538,
  false,
  118,
  NULL,
  NULL,
  'DeShawn R.',
  NOW() - INTERVAL '2 days 20 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] Menominee Park trails need maintenance badly
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-14',
  'statement',
  'local',
  'Menominee Park trails need maintenance badly',
  'Fallen trees blocking paths, erosion near the lakefront, and the boardwalk has loose boards. A hazard for joggers and families.',
  'parks',
  'Menominee Park',
  44.018, -88.53,
  false,
  112,
  NULL,
  NULL,
  'Natalie K.',
  NOW() - INTERVAL '6 days 22 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] Empty storefront on Main St — can we attract new businesses?
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-15',
  'statement',
  'local',
  'Empty storefront on Main St — can we attract new businesses?',
  'The old hardware store has been vacant for over a year. Would love to see a community co-op, bookstore, or local coffee shop move in.',
  'business',
  'Main St',
  44.025, -88.545,
  false,
  158,
  NULL,
  NULL,
  'Jamie L.',
  NOW() - INTERVAL '0 days 12 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-15-c15a', p.id, 'A food co-op would be incredible there. Central location, good parking.', false,
  0, 'Natalie K.', NOW() - INTERVAL '3 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-15'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Water main break on Washington Ave flooding basements
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-16',
  'statement',
  'local',
  'Water main break on Washington Ave flooding basements',
  'Multiple homes on the 400 block have flooded basements. The city sent trucks but the leak is still going. Need emergency response.',
  'other',
  'Washington Ave',
  44.022, -88.547,
  false,
  287,
  NULL,
  NULL,
  'Marcus T.',
  NOW() - INTERVAL '4 days 1 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-16-c16a', p.id, 'This happened last spring too. The pipes on this block are ancient.', false,
  0, 'OshkoshNative', NOW() - INTERVAL '22 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-16'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-16-c16b', p.id, 'My neighbor lost thousands in damages. Insurance won''t cover it.', false,
  0, 'CommuteDad', NOW() - INTERVAL '15 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-16'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] GO Transit needs Sunday service
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-17',
  'statement',
  'local',
  'GO Transit needs Sunday service',
  'No buses on Sunday means no way to get to work for those without cars. This hurts service workers the most.',
  'transit',
  'Citywide',
  44.024, -88.543,
  false,
  124,
  NULL,
  NULL,
  'DeShawn R.',
  NOW() - INTERVAL '3 days 15 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-17-c17a', p.id, 'I have to spend $25 on Uber every Sunday just to get to my shift. That''s $100/month.', false,
  0, 'BusRider22', NOW() - INTERVAL '27 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-17'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Landlord refuses to fix heating — 3 months and counting
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-18',
  'statement',
  'local',
  'Landlord refuses to fix heating — 3 months and counting',
  'Reported broken heating in January. It''s still not fixed. Landlord ignores calls. Is there a tenant protection office in Oshkosh?',
  'housing',
  'Near UW Oshkosh',
  44.028, -88.554,
  true,
  96,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL '1 days 2 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-18-c18a', p.id, 'Contact the city building inspector. They can force the landlord to act.', false,
  0, 'Desiree W.', NOW() - INTERVAL '17 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-18'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] The Pollock Community Water Park is a gem
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-19',
  'statement',
  'local',
  'The Pollock Community Water Park is a gem',
  'Took the kids this weekend and it was spotless, well-staffed, and affordable. Oshkosh gets this right.',
  'compliment',
  'Pollock Water Park',
  44.017, -88.54,
  false,
  152,
  NULL,
  NULL,
  'Desiree W.',
  NOW() - INTERVAL '3 days 18 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] Speeding on Murdock Ave is out of control
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-20',
  'statement',
  'local',
  'Speeding on Murdock Ave is out of control',
  'People treating it like a highway. Speed bumps or radar signs are needed before someone gets killed.',
  'safety',
  'Murdock Ave',
  44.019, -88.536,
  false,
  201,
  NULL,
  NULL,
  'Marcus T.',
  NOW() - INTERVAL '5 days 4 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-20-c20a', p.id, 'Agreed. I''ve seen people doing 50+ in a 25 zone.', false,
  0, 'CommuteDad', NOW() - INTERVAL '11 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-20'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Dog park at Fuechsl Park needs a water fountain
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-21',
  'statement',
  'local',
  'Dog park at Fuechsl Park needs a water fountain',
  'Great dog park but no water source. In summer, dogs are overheating. A simple fountain would make a huge difference.',
  'parks',
  'Fuechsl Park',
  44.03, -88.55,
  false,
  67,
  NULL,
  NULL,
  'Natalie K.',
  NOW() - INTERVAL '6 days 18 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] New Arby's on Koeller — do we really need another fast food chain?
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-22',
  'statement',
  'local',
  'New Arby''s on Koeller — do we really need another fast food chain?',
  'Would much rather see local restaurants get support. The Koeller strip is already nothing but chains.',
  'business',
  'Koeller St',
  44.016, -88.536,
  false,
  94,
  NULL,
  NULL,
  'Jamie L.',
  NOW() - INTERVAL '4 days 20 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-22-c22a', p.id, 'Oshkosh has amazing local food. We should be promoting that, not more chains.', false,
  0, 'ArtLover', NOW() - INTERVAL '48 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-22'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Graffiti under the Ceape Ave bridge getting worse
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-23',
  'statement',
  'local',
  'Graffiti under the Ceape Ave bridge getting worse',
  'What used to be harmless tags is now vulgar and gang-related. Needs cleanup and maybe a legal mural wall instead.',
  'safety',
  'Ceape Ave Bridge',
  44.023, -88.541,
  true,
  71,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL '5 days 2 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] Library summer reading program is fantastic
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-24',
  'statement',
  'local',
  'Library summer reading program is fantastic',
  'The Oshkosh Public Library just announced their summer lineup. Free programs for kids of all ages. This community investment pays off.',
  'compliment',
  'Oshkosh Public Library',
  44.025, -88.544,
  false,
  78,
  NULL,
  NULL,
  'Jamie L.',
  NOW() - INTERVAL '1 days 9 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-24-c24a', p.id, 'My kids look forward to this every year. Thank you to the library staff!', false,
  0, 'Desiree W.', NOW() - INTERVAL '11 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-24'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Pot smell from apartment complex — is this legal?
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-25',
  'statement',
  'local',
  'Pot smell from apartment complex — is this legal?',
  'The hallways in my building reek constantly. Other tenants have complained but management does nothing.',
  'noise',
  'Near Pioneer Dr',
  44.015, -88.548,
  true,
  47,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL '6 days 7 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] Sidewalk on High Ave is crumbling — wheelchair inaccessible
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-26',
  'statement',
  'local',
  'Sidewalk on High Ave is crumbling — wheelchair inaccessible',
  'My mother uses a wheelchair and can''t navigate High Ave anymore. The sidewalk is broken up and there are no curb cuts.',
  'pothole',
  'High Ave',
  44.026, -88.546,
  false,
  218,
  NULL,
  NULL,
  'Desiree W.',
  NOW() - INTERVAL '6 days 1 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-26-c26a', p.id, 'ADA compliance isn''t optional. The city needs to fix this.', false,
  0, 'BusRider22', NOW() - INTERVAL '28 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-26'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Free little libraries popping up everywhere — love it
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-27',
  'statement',
  'local',
  'Free little libraries popping up everywhere — love it',
  'Counted 4 new little free libraries on my walk today. Neighbors sharing books is peak community.',
  'compliment',
  'Various neighborhoods',
  44.021, -88.551,
  false,
  68,
  NULL,
  NULL,
  'Natalie K.',
  NOW() - INTERVAL '0 days 1 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] Bus route 3 discontinued — how do I get to the east side?
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-28',
  'statement',
  'local',
  'Bus route 3 discontinued — how do I get to the east side?',
  'Route 3 was the only connection between west side neighborhoods and east side shopping. Now there''s a 2-mile gap with no transit.',
  'transit',
  'West Side',
  44.022, -88.558,
  false,
  108,
  NULL,
  NULL,
  'DeShawn R.',
  NOW() - INTERVAL '5 days 9 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] Wittman Airport noise has increased significantly
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-29',
  'statement',
  'local',
  'Wittman Airport noise has increased significantly',
  'More small aircraft running early morning and late evening flights. Is EAA prep already starting? Residents near the airport are losing sleep.',
  'noise',
  'Near Wittman Airport',
  44.029, -88.557,
  true,
  68,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL '1 days 13 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-29-c29a', p.id, 'It''s EAA season. It''ll only get louder from here through July.', false,
  0, 'OshkoshNative', NOW() - INTERVAL '29 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-29'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Can we get a crosstown bike trail like Appleton?
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-30',
  'statement',
  'local',
  'Can we get a crosstown bike trail like Appleton?',
  'Appleton has a connected trail system that goes from east to west. Oshkosh has patchwork trails that dead-end. Time to invest in connectivity.',
  'parks',
  'Citywide',
  44.024, -88.543,
  false,
  121,
  NULL,
  NULL,
  'Jamie L.',
  NOW() - INTERVAL '5 days 6 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-30-c30a', p.id, 'This would reduce traffic AND improve health outcomes. Win-win.', false,
  0, 'DeShawn R.', NOW() - INTERVAL '6 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-30'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Rent increase of $200/mo with zero improvements
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-31',
  'statement',
  'local',
  'Rent increase of $200/mo with zero improvements',
  'My landlord raised rent from $850 to $1050 with no upgrades. Same broken dishwasher, same stained carpet. Where do we go?',
  'housing',
  'South Side',
  44.018, -88.545,
  true,
  149,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL '5 days 12 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] Oshkosh Food Co-op just opened — support local!
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-32',
  'statement',
  'local',
  'Oshkosh Food Co-op just opened — support local!',
  'Local producers, fair prices, community-owned. This is what happens when neighbors invest in each other.',
  'business',
  'Downtown',
  44.025, -88.542,
  false,
  134,
  NULL,
  NULL,
  'Natalie K.',
  NOW() - INTERVAL '5 days 13 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-32-c32a', p.id, 'Their local cheese selection is incredible. So proud of this city.', false,
  0, 'Natalie K.', NOW() - INTERVAL '18 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-32'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Flooding on Smith Ave after every heavy rain
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-33',
  'statement',
  'local',
  'Flooding on Smith Ave after every heavy rain',
  'Storm drains are clearly blocked or undersized. The road becomes impassable. Cars have been stranded.',
  'other',
  'Smith Ave',
  44.02, -88.537,
  false,
  143,
  NULL,
  NULL,
  'Marcus T.',
  NOW() - INTERVAL '4 days 16 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [local] What color theme should the new flower beds on Main Street feature thi
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-q1',
  'question',
  'local',
  'What color theme should the new flower beds on Main Street feature this spring?',
  'Public Works has the budget approved and is asking residents to weigh in. The top-voted answer will be the consensus recommendation sent to City Hall.',
  'parks',
  'Main Street',
  44.025, -88.544,
  false,
  89,
  NULL,
  NULL,
  'Jamie L.',
  NOW() - INTERVAL '5 days 9 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q1-q1c1', p.id, 'Wildflower mix — pollinator-friendly, supports our bees, low maintenance.', false,
  124, 'Natalie K.', NOW() - INTERVAL '24 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q1'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q1-q1c2', p.id, 'Blue and gold — Oshkosh colors. City pride right on Main.', false,
  47, 'OshkoshNative', NOW() - INTERVAL '23 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q1'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q1-q1c3', p.id, 'All white — classic, photogenic, works against any backdrop.', false,
  31, 'Jamie L.', NOW() - INTERVAL '14 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q1'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q1-q1c4', p.id, 'Sunset palette — orange, red, yellow. Stands out from a block away.', false,
  18, 'ArtLover', NOW() - INTERVAL '26 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q1'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] What should we name the new pocket park opening on 9th Ave?
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-q2',
  'question',
  'local',
  'What should we name the new pocket park opening on 9th Ave?',
  'The new park between Oregon and Jackson opens this fall. The Parks Department is taking community submissions for the name.',
  'parks',
  '9th Ave',
  44.024, -88.541,
  false,
  134,
  NULL,
  NULL,
  'Marcus T.',
  NOW() - INTERVAL '0 days 5 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q2-q2c1', p.id, 'Marian Memorial Park — name it after Marian Schultz, the neighborhood advocate who passed last year. She fought for this lot for twenty years.', false,
  178, 'Desiree W.', NOW() - INTERVAL '23 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q2'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q2-q2c2', p.id, 'Lakeside Commons — simple, evergreen, ties to the city identity.', false,
  56, 'Marcus T.', NOW() - INTERVAL '2 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q2'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q2-q2c3', p.id, 'Founders Green — honors the city heritage without picking one name.', false,
  42, 'OshkoshNative', NOW() - INTERVAL '23 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q2'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q2-q2c4', p.id, 'Just call it 9th Avenue Park. Easy to find, easy to remember.', false,
  21, 'CommuteDad', NOW() - INTERVAL '12 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q2'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Where should the next dog park be built — north side or south side?
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-q3',
  'question',
  'local',
  'Where should the next dog park be built — north side or south side?',
  'Fuechsl is consistently overcrowded. Parks Dept has funding for one new dog park and is asking residents which neighborhood needs it most.',
  'parks',
  'Citywide',
  44.024, -88.544,
  false,
  102,
  NULL,
  NULL,
  'Desiree W.',
  NOW() - INTERVAL '6 days 4 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q3-q3c1', p.id, 'North side — Fuechsl already covers the center and south. Nothing exists past Murdock.', false,
  87, 'DeShawn R.', NOW() - INTERVAL '35 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q3'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q3-q3c2', p.id, 'South side — closer to the highest-density apartments where dog owners actually live.', false,
  64, 'Desiree W.', NOW() - INTERVAL '43 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q3'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q3-q3c3', p.id, 'Honestly both. Fuechsl is unusable on weekends. We need at least one more, period.', false,
  39, 'Natalie K.', NOW() - INTERVAL '1 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q3'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] What's the best pizza in Oshkosh?
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-q5',
  'question',
  'local',
  'What''s the best pizza in Oshkosh?',
  'Settling this once and for all. Drop your pick in the answers — the top-voted reply becomes the community Verdict.',
  'business',
  'Oshkosh',
  44.024, -88.543,
  false,
  218,
  NULL,
  NULL,
  'Marcus T.',
  NOW() - INTERVAL '0 days 4 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q5-q5c1', p.id, 'Dr. Benzies. If you know, you know — and if you don''t, the line out the door on a Friday should tell you.', false,
  287, 'OshkoshNative', NOW() - INTERVAL '20 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q5'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q5-q5c2', p.id, 'Polito''s after 11pm. Different rules apply.', false,
  156, 'Marcus T.', NOW() - INTERVAL '26 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q5'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q5-q5c3', p.id, 'Mark''s East Side. It''s a bar, sure, but the pizza is what brings me back.', false,
  121, 'CommuteDad', NOW() - INTERVAL '2 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q5'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q5-q5c4', p.id, 'Dr. Benzies for the pie itself, Polito''s for late night, Mark''s for a beer with it. Best pizza is contextual.', false,
  142, 'Jamie L.', NOW() - INTERVAL '20 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q5'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q5-q5c5', p.id, 'Honestly, Benzies hasn''t missed in years. Hard to argue with consistency.', false,
  98, 'BusRider22', NOW() - INTERVAL '37 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q5'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q5-q5c6', p.id, 'Hot take: Polito''s is fine but it''s the bar food of pizza. Benzies is the actual pizza.', false,
  73, 'ArtLover', NOW() - INTERVAL '27 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q5'
ON CONFLICT (seed_key) DO NOTHING;

-- [local] Should the downtown farmers market stay on Saturdays or move to Sunday
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-q4',
  'question',
  'local',
  'Should the downtown farmers market stay on Saturdays or move to Sunday mornings?',
  'Vendors are split. Saturday traffic competes with downtown events; Sunday opens family time. The market board is putting it to the community.',
  'business',
  'Downtown Oshkosh',
  44.025, -88.543,
  false,
  76,
  NULL,
  NULL,
  'Natalie K.',
  NOW() - INTERVAL '2 days 20 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q4-q4c1', p.id, 'Keep Saturday. Foot traffic from downtown events is what makes the market what it is.', false,
  92, 'Natalie K.', NOW() - INTERVAL '13 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q4'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q4-q4c2', p.id, 'Move to Sunday. Saturday mornings are already overcommitted for most families.', false,
  38, 'CommuteDad', NOW() - INTERVAL '10 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q4'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-q4-q4c3', p.id, 'Run it both days during peak season. Vendors win, residents win.', false,
  54, 'BusRider22', NOW() - INTERVAL '39 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-q4'
ON CONFLICT (seed_key) DO NOTHING;

-- [state] Wisconsin public school funding is falling behind neighboring states
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s1',
  'statement',
  'state',
  'Wisconsin public school funding is falling behind neighboring states',
  'Per-pupil spending in WI has dropped relative to Minnesota and Illinois over the past decade. Our kids deserve competitive investment in their education.',
  'education',
  'Statewide',
  NULL, NULL,
  false,
  1247,
  NULL,
  NULL,
  'Marcus T.',
  NOW() - INTERVAL '2 days 11 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-s1-sc1', p.id, 'Oshkosh schools have been asking for operating referendum after referendum. The state formula needs to change.', false,
  0, 'Marcus T.', NOW() - INTERVAL '37 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-s1'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-s1-sc2', p.id, 'As a teacher, I see this every day. We''re losing good educators to states that pay more.', false,
  0, 'Jamie L.', NOW() - INTERVAL '30 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-s1'
ON CONFLICT (seed_key) DO NOTHING;

-- [state] Expand Medicaid coverage to close the insurance gap
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s2',
  'statement',
  'state',
  'Expand Medicaid coverage to close the insurance gap',
  'Over 90,000 Wisconsinites fall in the coverage gap. Expanding BadgerCare would bring billions in federal funding back to our state.',
  'healthcare',
  'Statewide',
  NULL, NULL,
  false,
  934,
  NULL,
  NULL,
  'Desiree W.',
  NOW() - INTERVAL '5 days 11 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-s2-sc3', p.id, 'I know families who have to choose between groceries and prescriptions. This shouldn''t happen in Wisconsin.', false,
  0, 'Desiree W.', NOW() - INTERVAL '17 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-s2'
ON CONFLICT (seed_key) DO NOTHING;

-- [state] I-43 corridor desperately needs modernization
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s3',
  'statement',
  'state',
  'I-43 corridor desperately needs modernization',
  'The I-43 corridor between Milwaukee and Green Bay is one of the deadliest stretches in the state. Widening and safety upgrades are long overdue.',
  'infrastructure',
  'I-43 Corridor',
  NULL, NULL,
  true,
  672,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL '5 days 17 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [state] PFAS contamination in drinking water — where is the state action?
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s4',
  'statement',
  'state',
  'PFAS contamination in drinking water — where is the state action?',
  'Multiple communities across Wisconsin have detected PFAS "forever chemicals" in their water supply. We need statewide standards and cleanup funding now.',
  'environment',
  'Multiple Counties',
  NULL, NULL,
  false,
  1089,
  NULL,
  NULL,
  'Natalie K.',
  NOW() - INTERVAL '2 days 10 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-s4-sc4', p.id, 'This is a public health emergency. Marinette, La Crosse, and now Oshkosh — how many more communities?', false,
  0, 'OshkoshNative', NOW() - INTERVAL '42 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-s4'
ON CONFLICT (seed_key) DO NOTHING;

-- [state] State budget surplus should go back to taxpayers and roads
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s5',
  'statement',
  'state',
  'State budget surplus should go back to taxpayers and roads',
  'Wisconsin is sitting on a $4B+ surplus. Let''s invest it in crumbling infrastructure and provide tax relief instead of letting it sit in Madison.',
  'state-budget',
  'Madison, WI',
  NULL, NULL,
  false,
  856,
  NULL,
  NULL,
  'DeShawn R.',
  NOW() - INTERVAL '2 days 16 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-s5-sc5', p.id, 'Our local roads are falling apart while the state hoards cash. Makes no sense.', false,
  0, 'CommuteDad', NOW() - INTERVAL '36 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-s5'
ON CONFLICT (seed_key) DO NOTHING;

-- [state] Support the bipartisan redistricting reform bill
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s6',
  'statement',
  'state',
  'Support the bipartisan redistricting reform bill',
  'Fair maps mean fair representation. The nonpartisan redistricting commission bill has bipartisan support — let''s get it passed.',
  'legislation',
  'Madison, WI',
  NULL, NULL,
  true,
  743,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL '4 days 11 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [state] Make Election Day a state holiday for all workers
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s7',
  'statement',
  'state',
  'Make Election Day a state holiday for all workers',
  'Voter turnout suffers when people can''t get time off. Making Election Day a state holiday would strengthen our democracy.',
  'elections',
  'Statewide',
  NULL, NULL,
  false,
  612,
  NULL,
  NULL,
  'Jamie L.',
  NOW() - INTERVAL '2 days 12 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-s7-sc6', p.id, 'I had to choose between missing a shift and voting last cycle. That''s not right.', false,
  0, 'BusRider22', NOW() - INTERVAL '28 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-s7'
ON CONFLICT (seed_key) DO NOTHING;

-- [state] Statewide rent stabilization — do we need it?
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s8',
  'statement',
  'state',
  'Statewide rent stabilization — do we need it?',
  'Wisconsin currently bans cities from implementing rent control. With rents surging in Madison, Milwaukee, and college towns, should the state allow local rent stabilization measures?',
  'housing-policy',
  'Statewide',
  NULL, NULL,
  true,
  489,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL '0 days 1 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [state] Rural broadband is a crisis — half of northern WI has no reliable inte
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s9',
  'statement',
  'state',
  'Rural broadband is a crisis — half of northern WI has no reliable internet',
  'Students can''t do homework, businesses can''t operate, telehealth is impossible. The state needs to treat broadband like a utility.',
  'infrastructure',
  'Northern Wisconsin',
  NULL, NULL,
  false,
  891,
  NULL,
  NULL,
  'DeShawn R.',
  NOW() - INTERVAL '6 days 18 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-s9-sc9a', p.id, 'My cousins in Wausau have to drive to McDonald''s parking lot for wifi. In 2026.', false,
  0, 'Marcus T.', NOW() - INTERVAL '30 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-s9'
ON CONFLICT (seed_key) DO NOTHING;

-- [state] Childcare costs are forcing parents out of the workforce
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s10',
  'statement',
  'state',
  'Childcare costs are forcing parents out of the workforce',
  'Average childcare in WI costs $12,000+/year per child. Many parents — especially mothers — are leaving jobs because it''s cheaper to stay home.',
  'state-budget',
  'Statewide',
  NULL, NULL,
  false,
  1102,
  NULL,
  NULL,
  'Desiree W.',
  NOW() - INTERVAL '3 days 5 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-s10-sc10a', p.id, 'I pay more for childcare than my mortgage. Something has to give.', false,
  0, 'Desiree W.', NOW() - INTERVAL '29 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-s10'
ON CONFLICT (seed_key) DO NOTHING;

-- [state] Universal background checks for gun purchases — where does WI stand?
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s11',
  'statement',
  'state',
  'Universal background checks for gun purchases — where does WI stand?',
  'Wisconsin has no universal background check requirement for private sales. With gun violence rising, should we close this loophole?',
  'legislation',
  'Statewide',
  NULL, NULL,
  true,
  567,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL '0 days 14 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [state] Protect the Great Lakes from Line 5 pipeline risks
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s12',
  'statement',
  'state',
  'Protect the Great Lakes from Line 5 pipeline risks',
  'The Enbridge Line 5 pipeline under the Straits of Mackinac threatens the entire Great Lakes ecosystem. Wisconsin should join Michigan in demanding safety upgrades.',
  'environment',
  'Lake Michigan',
  NULL, NULL,
  false,
  783,
  NULL,
  NULL,
  'Natalie K.',
  NOW() - INTERVAL '1 days 6 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-s12-sc12a', p.id, 'Lake Michigan provides drinking water for millions. This should be non-negotiable.', false,
  0, 'Natalie K.', NOW() - INTERVAL '6 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-s12'
ON CONFLICT (seed_key) DO NOTHING;

-- [state] Wisconsin is losing skilled trades workers at an alarming rate
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s13',
  'statement',
  'state',
  'Wisconsin is losing skilled trades workers at an alarming rate',
  'Plumbers, electricians, and welders are retiring faster than we can replace them. The state needs to invest in technical college funding and apprenticeship programs.',
  'education',
  'Statewide',
  NULL, NULL,
  false,
  645,
  NULL,
  NULL,
  'Marcus T.',
  NOW() - INTERVAL '1 days 3 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-s13-sc13a', p.id, 'My plumber is booked 6 weeks out. We need to make trades attractive to young people again.', false,
  0, 'CommuteDad', NOW() - INTERVAL '23 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-s13'
ON CONFLICT (seed_key) DO NOTHING;

-- [state] Legalize and tax recreational cannabis — WI is surrounded
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s14',
  'statement',
  'state',
  'Legalize and tax recreational cannabis — WI is surrounded',
  'Illinois, Michigan, and Minnesota all have legal cannabis. Wisconsin residents are driving across state lines and WI is missing out on hundreds of millions in tax revenue.',
  'legislation',
  'Statewide',
  NULL, NULL,
  false,
  1389,
  NULL,
  NULL,
  'Jamie L.',
  NOW() - INTERVAL '6 days 19 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-s14-sc14a', p.id, 'Illinois made $1.5 BILLION in cannabis revenue last year. That money could fix our roads.', false,
  0, 'BusRider22', NOW() - INTERVAL '37 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-s14'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-s14-sc14b', p.id, 'The border dispensaries in Illinois are packed with WI plates. The revenue is already leaving the state.', false,
  0, 'ArtLover', NOW() - INTERVAL '1 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-s14'
ON CONFLICT (seed_key) DO NOTHING;

-- [state] Lead pipe replacement — 400,000 homes still at risk
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s15',
  'statement',
  'state',
  'Lead pipe replacement — 400,000 homes still at risk',
  'Wisconsin has one of the highest concentrations of lead service lines in the nation. Federal funding exists but the state needs to streamline the replacement process.',
  'healthcare',
  'Statewide',
  NULL, NULL,
  false,
  712,
  NULL,
  NULL,
  'Desiree W.',
  NOW() - INTERVAL '6 days 23 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [state] Mental health crisis: WI ranks 34th in access to care
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s16',
  'statement',
  'state',
  'Mental health crisis: WI ranks 34th in access to care',
  'Long wait times, shortage of providers, and stigma. Rural areas have almost no access. We need state-funded crisis centers and telehealth expansion.',
  'healthcare',
  'Statewide',
  NULL, NULL,
  false,
  834,
  NULL,
  NULL,
  'Jamie L.',
  NOW() - INTERVAL '2 days 21 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-s16-sc16a', p.id, 'As a teacher I see kids struggling with no resources. The waitlist for a school psychologist is 6 months.', false,
  0, 'Jamie L.', NOW() - INTERVAL '1 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-s16'
ON CONFLICT (seed_key) DO NOTHING;

-- [state] Property tax freeze for seniors on fixed incomes
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s17',
  'statement',
  'state',
  'Property tax freeze for seniors on fixed incomes',
  'Seniors who''ve lived in their homes for 30+ years are being taxed out. A freeze for residents over 65 earning under $50K would provide real relief.',
  'state-budget',
  'Statewide',
  NULL, NULL,
  false,
  923,
  NULL,
  NULL,
  'Marcus T.',
  NOW() - INTERVAL '0 days 13 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-s17-sc17a', p.id, 'My neighbor is 78 and might lose her home because of tax increases. She''s lived there 40 years.', false,
  0, 'OshkoshNative', NOW() - INTERVAL '7 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-s17'
ON CONFLICT (seed_key) DO NOTHING;

-- [state] Support Wisconsin dairy farmers — the backbone of our economy
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-s18',
  'statement',
  'state',
  'Support Wisconsin dairy farmers — the backbone of our economy',
  'Family dairy farms are closing at record rates. The state should invest in value-added processing, export markets, and farm succession planning.',
  'other-state',
  'Statewide',
  NULL, NULL,
  false,
  576,
  NULL,
  NULL,
  'Natalie K.',
  NOW() - INTERVAL '2 days 6 hours'
) ON CONFLICT (seed_key) DO NOTHING;

-- [state] Which state-owned forest deserves the next major trail investment?
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-sq1',
  'question',
  'state',
  'Which state-owned forest deserves the next major trail investment?',
  'The WI DNR has $3M earmarked for trail upgrades. Asking residents statewide which property would deliver the most use and economic return.',
  'environment',
  'Statewide',
  NULL, NULL,
  false,
  412,
  NULL,
  NULL,
  'Natalie K.',
  NOW() - INTERVAL '5 days 3 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-sq1-sq1c1', p.id, 'Northern Highland — those trails are the heart of the Northwoods tourism economy and they''re falling apart.', false,
  218, 'Natalie K.', NOW() - INTERVAL '9 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-sq1'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-sq1-sq1c2', p.id, 'Kettle Moraine — it absorbs the most volume from Milwaukee and Madison. Biggest ROI per dollar.', false,
  134, 'Marcus T.', NOW() - INTERVAL '9 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-sq1'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-sq1-sq1c3', p.id, 'Black River — the most underfunded and underused. Invest where the gap is biggest.', false,
  67, 'OshkoshNative', NOW() - INTERVAL '5 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-sq1'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-sq1-sq1c4', p.id, 'Point Beach — it serves the entire eastern shore. Trails there are basically gravel.', false,
  41, 'DeShawn R.', NOW() - INTERVAL '8 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-sq1'
ON CONFLICT (seed_key) DO NOTHING;

-- [state] What should Wisconsin's next state license plate design feature?
INSERT INTO posts (
  seed_key, type, scope, title, description, category, location_label,
  lat, lng, is_incognito, vote_count, media, impact,
  seed_author, created_at
) VALUES (
  'pulse-seed-post-sq2',
  'question',
  'state',
  'What should Wisconsin''s next state license plate design feature?',
  'The DOT is refreshing the standard plate for 2027. Residents are being asked what should represent the state on every car on the road.',
  'other-state',
  'Statewide',
  NULL, NULL,
  false,
  287,
  NULL,
  NULL,
  'Jamie L.',
  NOW() - INTERVAL '6 days 11 hours'
) ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-sq2-sq2c1', p.id, 'The Driftless Area landscape — most distinct geography we have, and nothing else has it.', false,
  156, 'Jamie L.', NOW() - INTERVAL '25 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-sq2'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-sq2-sq2c2', p.id, 'A simple modern badger silhouette. Clean, iconic, doesn''t go out of style.', false,
  198, 'CommuteDad', NOW() - INTERVAL '45 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-sq2'
ON CONFLICT (seed_key) DO NOTHING;

INSERT INTO comments (
  seed_key, post_id, text, is_incognito, vote_count, seed_author, created_at
)
SELECT 'pulse-seed-comment-sq2-sq2c3', p.id, 'Lake Michigan shoreline. The Great Lakes are the most important resource we have.', false,
  87, 'BusRider22', NOW() - INTERVAL '23 hours'
FROM posts p WHERE p.seed_key = 'pulse-seed-post-sq2'
ON CONFLICT (seed_key) DO NOTHING;

COMMIT;
