export const CATEGORIES = [
  { id: 'pothole', label: 'Potholes', icon: 'cat-pothole', emoji: '🕳️', color: '#FF6B35' },
  { id: 'safety', label: 'Safety', icon: 'cat-safety', emoji: '🚨', color: '#FF3366' },
  { id: 'noise', label: 'Noise', icon: 'cat-noise', emoji: '🔊', color: '#A855F7' },
  { id: 'parks', label: 'Parks', icon: 'cat-parks', emoji: '🌳', color: '#22C55E' },
  { id: 'transit', label: 'Transit', icon: 'cat-transit', emoji: '🚌', color: '#3B82F6' },
  { id: 'housing', label: 'Housing', icon: 'cat-housing', emoji: '🏠', color: '#F59E0B' },
  { id: 'business', label: 'Business', icon: 'cat-business', emoji: '🏪', color: '#EC4899' },
  { id: 'compliment', label: 'Compliment', icon: 'cat-compliment', emoji: '💚', color: '#10B981' },
  { id: 'other', label: 'Other', icon: 'cat-other', emoji: '📌', color: '#6B7280' },
]

export const STATE_CATEGORIES = [
  { id: 'education', label: 'Education', icon: 'cat-education', emoji: '🎓', color: '#6366F1' },
  { id: 'healthcare', label: 'Healthcare', icon: 'cat-healthcare', emoji: '🏥', color: '#EF4444' },
  { id: 'infrastructure', label: 'Infrastructure', icon: 'cat-infrastructure', emoji: '🛣️', color: '#F59E0B' },
  { id: 'environment', label: 'Environment', icon: 'cat-environment', emoji: '🌿', color: '#22C55E' },
  { id: 'state-budget', label: 'State Budget', icon: 'cat-state-budget', emoji: '💰', color: '#D97706' },
  { id: 'legislation', label: 'Legislation', icon: 'cat-legislation', emoji: '⚖️', color: '#8B5CF6' },
  { id: 'elections', label: 'Elections', icon: 'cat-elections', emoji: '🗳️', color: '#3B82F6' },
  { id: 'housing-policy', label: 'Housing Policy', icon: 'cat-housing-policy', emoji: '🏠', color: '#EC4899' },
  { id: 'other-state', label: 'Other', icon: 'cat-other-state', emoji: '📌', color: '#6B7280' },
]

// User profiles for seed data
export const SEED_USERS = {
  'marcus': {
    id: 'marcus',
    displayName: 'Marcus T.',
    avatar: '🧑🏾',
    bio: 'Born & raised in Oshkosh. Commuter, pothole reporter, community advocate.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Jan 2026',
  },
  'jamie': {
    id: 'jamie',
    displayName: 'Jamie L.',
    avatar: '👩🏻‍🎨',
    bio: 'Art teacher at Oshkosh North. Big fan of public art and walkable neighborhoods.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    isPro: true,
    joinedAt: 'Feb 2026',
  },
  'desiree': {
    id: 'desiree',
    displayName: 'Desiree W.',
    avatar: '👩🏽',
    bio: 'Mom of two. Parks matter. Safe playgrounds matter.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Feb 2026',
  },
  'deshawn': {
    id: 'deshawn',
    displayName: 'DeShawn R.',
    avatar: '👨🏿',
    bio: 'Essential worker who depends on GO Transit. Cyclist when the bus doesn\'t show.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Mar 2026',
  },
  'natalie': {
    id: 'natalie',
    displayName: 'Natalie K.',
    avatar: '👩🏼',
    bio: 'Local food advocate. Downtown small business supporter.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Jan 2026',
  },
  // Comment-only users
  'oshkoshnative': {
    id: 'oshkoshnative',
    displayName: 'OshkoshNative',
    avatar: '🏡',
    bio: 'Lifelong resident. Seen this city through thick and thin.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Jan 2026',
  },
  'commutedad': {
    id: 'commutedad',
    displayName: 'CommuteDad',
    avatar: '🚗',
    bio: 'Driving the kids to school and back. Roads matter.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Mar 2026',
  },
  'artlover': {
    id: 'artlover',
    displayName: 'ArtLover',
    avatar: '🎨',
    bio: 'Supporting creativity in public spaces.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Feb 2026',
  },
  'busrider22': {
    id: 'busrider22',
    displayName: 'BusRider22',
    avatar: '🚌',
    bio: 'Daily bus commuter. Reliable transit = economic mobility.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Mar 2026',
  },
}

export const SEED_POSTS = [
  {
    id: '1',
    title: 'Massive potholes on Main St near 9th Ave',
    description: 'Three huge potholes have been here for months. Multiple cars have been damaged. This needs immediate attention.',
    category: 'pothole',
    location: 'Main St & 9th Ave',
    scope: 'local',
    votes: 147,
    userVote: 0,
    comments: [
      { id: 'c1', author: 'OshkoshNative', authorId: 'oshkoshnative', text: 'I hit one of these last week and it bent my rim. $400 repair.', timestamp: Date.now() - 3600000 },
      { id: 'c2', author: 'CommuteDad', authorId: 'commutedad', text: 'The school bus route goes right through here too.', timestamp: Date.now() - 1800000 }
    ],
    media: [
      { type: 'image', preview: '/demo-photos/pothole-1.jpg' },
      { type: 'image', preview: '/demo-photos/pothole-2.jpg' }
    ],
    incognito: false,
    author: 'Marcus T.',
    authorId: 'marcus',
    authorVerified: true,
    createdAt: '2h ago',
    userId: 'marcus',
    lat: 44.025,
    lng: -88.544
  },
  {
    id: '2',
    title: 'Streetlights out on Algoma Blvd for 3 weeks',
    description: 'The entire block between Jackson and Division has no streetlights. Safety hazard at night.',
    category: 'safety',
    location: 'Algoma Blvd',
    scope: 'local',
    votes: 89,
    userVote: 0,
    comments: [],
    media: [
      { type: 'image', preview: '/demo-photos/streetlights-1.jpg' }
    ],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '5h ago',
    userId: 'other',
    lat: 44.022,
    lng: -88.550
  },
  {
    id: '3',
    title: 'New mural downtown looks incredible',
    description: 'Shoutout to whoever organized the mural project on Oregon St. More of this please!',
    category: 'compliment',
    location: 'Oregon St',
    scope: 'local',
    votes: 203,
    userVote: 0,
    comments: [
      { id: 'c3', author: 'ArtLover', authorId: 'artlover', text: 'The artist is from Milwaukee! They did an amazing job.', timestamp: Date.now() - 43200000 }
    ],
    media: [
      { type: 'image', preview: '/demo-photos/mural-1.jpg' },
      { type: 'image', preview: '/demo-photos/mural-2.jpg' }
    ],
    incognito: false,
    author: 'Jamie L.',
    authorId: 'jamie',
    authorVerified: true,
    createdAt: '1d ago',
    userId: 'jamie',
    lat: 44.024,
    lng: -88.541
  },
  {
    id: '4',
    title: 'Construction noise at 6am every Saturday',
    description: 'The new development on Jackson St starts heavy machinery at 6am on weekends. City ordinance says 8am.',
    category: 'noise',
    location: 'Jackson St',
    scope: 'local',
    votes: 64,
    userVote: 0,
    comments: [],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '1d ago',
    userId: 'other',
    lat: 44.028,
    lng: -88.538
  },
  {
    id: '5',
    title: 'South Park playground equipment is broken',
    description: 'Two swings are broken and the slide has a crack. Kids are still playing on it — someone could get hurt.',
    category: 'parks',
    location: 'South Park',
    scope: 'local',
    votes: 112,
    userVote: 0,
    comments: [],
    media: [
      { type: 'image', preview: '/demo-photos/playground-1.jpg' },
      { type: 'image', preview: '/demo-photos/playground-2.jpg' },
      { type: 'image', preview: '/demo-photos/playground-3.jpg' }
    ],
    incognito: false,
    author: 'Desiree W.',
    authorId: 'desiree',
    authorVerified: true,
    createdAt: '2d ago',
    userId: 'desiree',
    lat: 44.020,
    lng: -88.548
  },
  {
    id: '6',
    title: 'Route 21 bus always 10+ minutes late',
    description: 'I rely on public transit to get to work. The Route 21 bus has been consistently late for the past month. This affects dozens of riders daily.',
    category: 'transit',
    location: 'Route 21 — Murdock Ave',
    scope: 'local',
    votes: 78,
    userVote: 0,
    comments: [
      { id: 'c4', author: 'BusRider22', authorId: 'busrider22', text: 'Same here. I\'ve been late to work 3 times this month because of this.', timestamp: Date.now() - 7200000 }
    ],
    incognito: false,
    author: 'DeShawn R.',
    authorId: 'deshawn',
    authorVerified: true,
    createdAt: '3d ago',
    userId: 'deshawn',
    lat: 44.019,
    lng: -88.535
  },
  {
    id: '7',
    title: 'Shout out to the new downtown farmers market',
    description: 'Great variety, friendly vendors, and it brings the community together every Saturday. Love seeing Oshkosh thrive like this.',
    category: 'compliment',
    location: 'Downtown Oshkosh',
    scope: 'local',
    votes: 245,
    userVote: 0,
    comments: [],
    media: [
      { type: 'image', preview: '/demo-photos/farmers-market-1.jpg' },
      { type: 'image', preview: '/demo-photos/farmers-market-2.jpg' },
      { type: 'image', preview: '/demo-photos/farmers-market-3.jpg' },
      { type: 'image', preview: '/demo-photos/farmers-market-4.jpg' }
    ],
    incognito: false,
    author: 'Natalie K.',
    authorId: 'natalie',
    authorVerified: true,
    createdAt: '4d ago',
    userId: 'natalie',
    lat: 44.024,
    lng: -88.543
  },
  {
    id: '8',
    title: 'Affordable housing near campus is disappearing',
    description: 'Every apartment near UWO is being converted to luxury units. Students and low-income families are being priced out.',
    category: 'housing',
    location: 'Near UW Oshkosh',
    scope: 'local',
    votes: 134,
    userVote: 0,
    comments: [],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '5d ago',
    userId: 'other',
    lat: 44.027,
    lng: -88.553
  }
]

export const STATE_SEED_POSTS = [
  {
    id: 's1',
    title: 'Wisconsin public school funding is falling behind neighboring states',
    description: 'Per-pupil spending in WI has dropped relative to Minnesota and Illinois over the past decade. Our kids deserve competitive investment in their education.',
    category: 'education',
    location: 'Statewide',
    scope: 'state',
    votes: 1247,
    userVote: 0,
    comments: [
      { id: 'sc1', author: 'Marcus T.', authorId: 'marcus', text: 'Oshkosh schools have been asking for operating referendum after referendum. The state formula needs to change.', timestamp: Date.now() - 7200000 },
      { id: 'sc2', author: 'Jamie L.', authorId: 'jamie', text: 'As a teacher, I see this every day. We\'re losing good educators to states that pay more.', timestamp: Date.now() - 3600000 }
    ],
    incognito: false,
    author: 'Marcus T.',
    authorId: 'marcus',
    authorVerified: true,
    createdAt: '6h ago',
    userId: 'marcus',
    lat: null,
    lng: null
  },
  {
    id: 's2',
    title: 'Expand Medicaid coverage to close the insurance gap',
    description: 'Over 90,000 Wisconsinites fall in the coverage gap. Expanding BadgerCare would bring billions in federal funding back to our state.',
    category: 'healthcare',
    location: 'Statewide',
    scope: 'state',
    votes: 934,
    userVote: 0,
    comments: [
      { id: 'sc3', author: 'Desiree W.', authorId: 'desiree', text: 'I know families who have to choose between groceries and prescriptions. This shouldn\'t happen in Wisconsin.', timestamp: Date.now() - 14400000 }
    ],
    incognito: false,
    author: 'Desiree W.',
    authorId: 'desiree',
    authorVerified: true,
    createdAt: '1d ago',
    userId: 'desiree',
    lat: null,
    lng: null
  },
  {
    id: 's3',
    title: 'I-43 corridor desperately needs modernization',
    description: 'The I-43 corridor between Milwaukee and Green Bay is one of the deadliest stretches in the state. Widening and safety upgrades are long overdue.',
    category: 'infrastructure',
    location: 'I-43 Corridor',
    scope: 'state',
    votes: 672,
    userVote: 0,
    comments: [],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '2d ago',
    userId: 'other',
    lat: null,
    lng: null
  },
  {
    id: 's4',
    title: 'PFAS contamination in drinking water — where is the state action?',
    description: 'Multiple communities across Wisconsin have detected PFAS "forever chemicals" in their water supply. We need statewide standards and cleanup funding now.',
    category: 'environment',
    location: 'Multiple Counties',
    scope: 'state',
    votes: 1089,
    userVote: 0,
    comments: [
      { id: 'sc4', author: 'OshkoshNative', authorId: 'oshkoshnative', text: 'This is a public health emergency. Marinette, La Crosse, and now Oshkosh — how many more communities?', timestamp: Date.now() - 28800000 }
    ],
    incognito: false,
    author: 'Natalie K.',
    authorId: 'natalie',
    authorVerified: true,
    createdAt: '3d ago',
    userId: 'natalie',
    lat: null,
    lng: null
  },
  {
    id: 's5',
    title: 'State budget surplus should go back to taxpayers and roads',
    description: 'Wisconsin is sitting on a $4B+ surplus. Let\'s invest it in crumbling infrastructure and provide tax relief instead of letting it sit in Madison.',
    category: 'state-budget',
    location: 'Madison, WI',
    scope: 'state',
    votes: 856,
    userVote: 0,
    comments: [
      { id: 'sc5', author: 'CommuteDad', authorId: 'commutedad', text: 'Our local roads are falling apart while the state hoards cash. Makes no sense.', timestamp: Date.now() - 36000000 }
    ],
    incognito: false,
    author: 'DeShawn R.',
    authorId: 'deshawn',
    authorVerified: true,
    createdAt: '4d ago',
    userId: 'deshawn',
    lat: null,
    lng: null
  },
  {
    id: 's6',
    title: 'Support the bipartisan redistricting reform bill',
    description: 'Fair maps mean fair representation. The nonpartisan redistricting commission bill has bipartisan support — let\'s get it passed.',
    category: 'legislation',
    location: 'Madison, WI',
    scope: 'state',
    votes: 743,
    userVote: 0,
    comments: [],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '5d ago',
    userId: 'other',
    lat: null,
    lng: null
  },
  {
    id: 's7',
    title: 'Make Election Day a state holiday for all workers',
    description: 'Voter turnout suffers when people can\'t get time off. Making Election Day a state holiday would strengthen our democracy.',
    category: 'elections',
    location: 'Statewide',
    scope: 'state',
    votes: 612,
    userVote: 0,
    comments: [
      { id: 'sc6', author: 'BusRider22', authorId: 'busrider22', text: 'I had to choose between missing a shift and voting last cycle. That\'s not right.', timestamp: Date.now() - 43200000 }
    ],
    incognito: false,
    author: 'Jamie L.',
    authorId: 'jamie',
    authorVerified: true,
    createdAt: '6d ago',
    userId: 'jamie',
    lat: null,
    lng: null
  },
  {
    id: 's8',
    title: 'Statewide rent stabilization — do we need it?',
    description: 'Wisconsin currently bans cities from implementing rent control. With rents surging in Madison, Milwaukee, and college towns, should the state allow local rent stabilization measures?',
    category: 'housing-policy',
    location: 'Statewide',
    scope: 'state',
    votes: 489,
    userVote: 0,
    comments: [],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '1w ago',
    userId: 'other',
    lat: null,
    lng: null
  }
]
