export const CATEGORIES = [
  { id: 'pothole', label: 'Potholes', icon: 'cat-pothole', emoji: '🕳️', color: '#FF6B35' },
  { id: 'safety', label: 'Safety', icon: 'cat-safety', emoji: '🚨', color: '#FF3366' },
  { id: 'noise', label: 'Noise', icon: 'cat-noise', emoji: '🔊', color: '#A855F7' },
  { id: 'parks', label: 'Parks', icon: 'cat-parks', emoji: '🌳', color: '#22C55E' },
  { id: 'transit', label: 'Transit', icon: 'cat-transit', emoji: '🚌', color: '#3B82F6' },
  { id: 'housing', label: 'Housing', icon: 'cat-housing', emoji: '🏠', color: '#F59E0B' },
  { id: 'business', label: 'Business', icon: 'cat-business', emoji: '🏪', color: '#EC4899' },
  { id: 'compliment', label: 'Compliment', icon: 'cat-compliment', emoji: '💚', color: '#10B981' },
  { id: 'other', label: 'Other', icon: 'cat-other', emoji: '📌', color: '#6B7280' },
]

export const STATE_CATEGORIES = [
  { id: 'education', label: 'Education', icon: 'cat-education', emoji: '🎓', color: '#6366F1' },
  { id: 'healthcare', label: 'Healthcare', icon: 'cat-healthcare', emoji: '🏥', color: '#EF4444' },
  { id: 'infrastructure', label: 'Infrastructure', icon: 'cat-infrastructure', emoji: '🛣️', color: '#F59E0B' },
  { id: 'environment', label: 'Environment', icon: 'cat-environment', emoji: '🌿', color: '#22C55E' },
  { id: 'state-budget', label: 'State Budget', icon: 'cat-state-budget', emoji: '💰', color: '#D97706' },
  { id: 'legislation', label: 'Legislation', icon: 'cat-legislation', emoji: '⚖️', color: '#8B5CF6' },
  { id: 'elections', label: 'Elections', icon: 'cat-elections', emoji: '🗳️', color: '#3B82F6' },
  { id: 'housing-policy', label: 'Housing Policy', icon: 'cat-housing-policy', emoji: '🏠', color: '#EC4899' },
  { id: 'other-state', label: 'Other', icon: 'cat-other-state', emoji: '📌', color: '#6B7280' },
]

// User profiles for seed data
export const SEED_USERS = {
  'marcus': {
    id: 'marcus',
    displayName: 'Marcus T.',
    avatar: '🧑🏾',
    bio: 'Born & raised in Oshkosh. Commuter, pothole reporter, community advocate.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Jan 2026',
    watching: ['1', '6', 's1'],
  },
  'jamie': {
    id: 'jamie',
    displayName: 'Jamie L.',
    avatar: '👩🏻‍🎨',
    bio: 'Art teacher at Oshkosh North. Big fan of public art and walkable neighborhoods.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    isPro: true,
    joinedAt: 'Feb 2026',
    watching: ['3', '5', 's1'],
  },
  'desiree': {
    id: 'desiree',
    displayName: 'Desiree W.',
    avatar: '👩🏽',
    bio: 'Mom of two. Parks matter. Safe playgrounds matter.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Feb 2026',
    watching: ['4', '2', 's2'],
  },
  'deshawn': {
    id: 'deshawn',
    displayName: 'DeShawn R.',
    avatar: '👨🏿',
    bio: 'Essential worker who depends on GO Transit. Cyclist when the bus doesn\'t show.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Mar 2026',
    watching: ['6', '1', 's5'],
  },
  'natalie': {
    id: 'natalie',
    displayName: 'Natalie K.',
    avatar: '👩🏼',
    bio: 'Local food advocate. Downtown small business supporter.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Jan 2026',
    watching: ['7', '3'],
  },
  // Comment-only users
  'oshkoshnative': {
    id: 'oshkoshnative',
    displayName: 'OshkoshNative',
    avatar: '🏡',
    bio: 'Lifelong resident. Seen this city through thick and thin.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Jan 2026',
  },
  'commutedad': {
    id: 'commutedad',
    displayName: 'CommuteDad',
    avatar: '🚗',
    bio: 'Driving the kids to school and back. Roads matter.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Mar 2026',
  },
  'artlover': {
    id: 'artlover',
    displayName: 'ArtLover',
    avatar: '🎨',
    bio: 'Supporting creativity in public spaces.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Feb 2026',
  },
  'busrider22': {
    id: 'busrider22',
    displayName: 'BusRider22',
    avatar: '🚌',
    bio: 'Daily bus commuter. Reliable transit = economic mobility.',
    city: 'Oshkosh',
    state: 'WI',
    isVerified: true,
    joinedAt: 'Mar 2026',
  },
}

export const SEED_POSTS = [
  {
    id: '1',
    title: 'Massive potholes on Main St near 9th Ave',
    description: 'Three huge potholes have been here for months. Multiple cars have been damaged. This needs immediate attention.',
    category: 'pothole',
    location: 'Main St & 9th Ave',
    scope: 'local',
    votes: 234,
    userVote: 0,
    comments: [
      { id: 'c1', author: 'OshkoshNative', authorId: 'oshkoshnative', text: 'I hit one of these last week and it bent my rim. $400 repair.', timestamp: Date.now() - 3600000 },
      { id: 'c2', author: 'CommuteDad', authorId: 'commutedad', text: 'The school bus route goes right through here too.', timestamp: Date.now() - 1800000 }
    ],
    media: [
      { type: 'image', preview: '/demo-photos/pothole-1.jpg' },
      { type: 'image', preview: '/demo-photos/pothole-2.jpg' }
    ],
    incognito: false,
    author: 'Marcus T.',
    authorId: 'marcus',
    authorVerified: true,
    createdAt: '2h ago',
    userId: 'marcus',
    lat: 44.025,
    lng: -88.544
  },
  {
    id: '2',
    title: 'Streetlights out on Algoma Blvd for 3 weeks',
    description: 'The entire block between Jackson and Division has no streetlights. Safety hazard at night.',
    category: 'safety',
    location: 'Algoma Blvd',
    scope: 'local',
    votes: 168,
    userVote: 0,
    comments: [],
    media: [
      { type: 'image', preview: '/demo-photos/streetlights-1.jpg' }
    ],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '5h ago',
    userId: 'other',
    lat: 44.022,
    lng: -88.550
  },
  {
    id: '3',
    title: 'New mural downtown looks incredible',
    description: 'Shoutout to whoever organized the mural project on Oregon St. More of this please!',
    category: 'compliment',
    location: 'Oregon St',
    scope: 'local',
    votes: 174,
    userVote: 0,
    comments: [
      { id: 'c3', author: 'ArtLover', authorId: 'artlover', text: 'The artist is from Milwaukee! They did an amazing job.', timestamp: Date.now() - 43200000 }
    ],
    media: [
      { type: 'image', preview: '/demo-photos/mural-1.jpg' },
      { type: 'image', preview: '/demo-photos/mural-2.jpg' }
    ],
    incognito: false,
    author: 'Jamie L.',
    authorId: 'jamie',
    authorVerified: true,
    createdAt: '1d ago',
    userId: 'jamie',
    lat: 44.024,
    lng: -88.541
  },
  {
    id: '4',
    title: 'Construction noise at 6am every Saturday',
    description: 'The new development on Jackson St starts heavy machinery at 6am on weekends. City ordinance says 8am.',
    category: 'noise',
    location: 'Jackson St',
    scope: 'local',
    votes: 87,
    userVote: 0,
    comments: [],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '1d ago',
    userId: 'other',
    lat: 44.028,
    lng: -88.538
  },
  {
    id: '5',
    title: 'South Park playground equipment is broken',
    description: 'Two swings are broken and the slide has a crack. Kids are still playing on it — someone could get hurt.',
    category: 'parks',
    location: 'South Park',
    scope: 'local',
    votes: 128,
    userVote: 0,
    comments: [],
    media: [
      { type: 'image', preview: '/demo-photos/playground-1.jpg' },
      { type: 'image', preview: '/demo-photos/playground-2.jpg' },
      { type: 'image', preview: '/demo-photos/playground-3.jpg' }
    ],
    incognito: false,
    author: 'Desiree W.',
    authorId: 'desiree',
    authorVerified: true,
    createdAt: '2d ago',
    userId: 'desiree',
    lat: 44.020,
    lng: -88.548
  },
  {
    id: '6',
    title: 'Route 21 bus always 10+ minutes late',
    description: 'I rely on public transit to get to work. The Route 21 bus has been consistently late for the past month. This affects dozens of riders daily.',
    category: 'transit',
    location: 'Route 21 — Murdock Ave',
    scope: 'local',
    votes: 119,
    userVote: 0,
    comments: [
      { id: 'c4', author: 'BusRider22', authorId: 'busrider22', text: 'Same here. I\'ve been late to work 3 times this month because of this.', timestamp: Date.now() - 7200000 }
    ],
    incognito: false,
    author: 'DeShawn R.',
    authorId: 'deshawn',
    authorVerified: true,
    createdAt: '3d ago',
    userId: 'deshawn',
    lat: 44.019,
    lng: -88.535
  },
  {
    id: '7',
    title: 'Shout out to the new downtown farmers market',
    description: 'Great variety, friendly vendors, and it brings the community together every Saturday. Love seeing Oshkosh thrive like this.',
    category: 'compliment',
    location: 'Downtown Oshkosh',
    scope: 'local',
    votes: 89,
    userVote: 0,
    comments: [],
    media: [
      { type: 'image', preview: '/demo-photos/farmers-market-1.jpg' },
      { type: 'image', preview: '/demo-photos/farmers-market-2.jpg' },
      { type: 'image', preview: '/demo-photos/farmers-market-3.jpg' },
      { type: 'image', preview: '/demo-photos/farmers-market-4.jpg' }
    ],
    incognito: false,
    author: 'Natalie K.',
    authorId: 'natalie',
    authorVerified: true,
    createdAt: '4d ago',
    userId: 'natalie',
    lat: 44.024,
    lng: -88.543
  },
  {
    id: '8',
    title: 'Affordable housing near campus is disappearing',
    description: 'Every apartment near UWO is being converted to luxury units. Students and low-income families are being priced out.',
    category: 'housing',
    location: 'Near UW Oshkosh',
    scope: 'local',
    votes: 187,
    userVote: 0,
    comments: [],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '5d ago',
    userId: 'other',
    lat: 44.027,
    lng: -88.553
  },
  {
    id: '9',
    title: 'Crosswalk on Witzel Ave is barely visible',
    description: 'The paint has completely faded. Cars blow through it constantly. Someone is going to get hit.',
    category: 'safety',
    location: 'Witzel Ave & Westfield',
    scope: 'local',
    votes: 142,
    userVote: 0,
    comments: [
      { id: 'c9a', author: 'CommuteDad', authorId: 'commutedad', text: 'My kids cross here every day for school. Terrifying.', timestamp: Date.now() - 5400000 }
    ],
    incognito: false,
    author: 'Desiree W.',
    authorId: 'desiree',
    authorVerified: true,
    createdAt: '3h ago',
    userId: 'desiree',
    lat: 44.021,
    lng: -88.556
  },
  {
    id: '10',
    title: 'Thank you Oshkosh PD for the community cookout',
    description: 'Officers grilling burgers and playing basketball with neighborhood kids. This is what community policing looks like.',
    category: 'compliment',
    location: 'Menominee Park',
    scope: 'local',
    votes: 72,
    userVote: 0,
    comments: [
      { id: 'c10a', author: 'OshkoshNative', authorId: 'oshkoshnative', text: 'This is the Oshkosh I grew up in. More of this please.', timestamp: Date.now() - 7200000 }
    ],
    incognito: false,
    author: 'Marcus T.',
    authorId: 'marcus',
    authorVerified: true,
    createdAt: '6h ago',
    userId: 'marcus',
    lat: 44.019,
    lng: -88.532
  },
  {
    id: '11',
    title: 'Sinkhole forming on Ohio St near the bridge',
    description: 'The road is literally caving in. You can see the ground shifting. This is a disaster waiting to happen.',
    category: 'pothole',
    location: 'Ohio St Bridge',
    scope: 'local',
    votes: 256,
    userVote: 0,
    comments: [],
    incognito: false,
    author: 'DeShawn R.',
    authorId: 'deshawn',
    authorVerified: true,
    createdAt: '8h ago',
    userId: 'deshawn',
    lat: 44.023,
    lng: -88.539
  },
  {
    id: '12',
    title: 'Bar noise on Oregon St until 3am every weekend',
    description: 'Bass-heavy music shaking our windows. We have a 6-month-old baby. The noise ordinance clearly isn\'t enforced.',
    category: 'noise',
    location: 'Oregon St',
    scope: 'local',
    votes: 96,
    userVote: 0,
    comments: [
      { id: 'c12a', author: 'ArtLover', authorId: 'artlover', text: 'I love Oregon St but the late night noise is getting out of control.', timestamp: Date.now() - 14400000 }
    ],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '10h ago',
    userId: 'other',
    lat: 44.024,
    lng: -88.542
  },
  {
    id: '13',
    title: 'New bike lanes on Jackson St are amazing',
    description: 'Finally feel safe biking to work. Protected lanes, clear markings, and drivers are actually respecting them.',
    category: 'compliment',
    location: 'Jackson St',
    scope: 'local',
    votes: 118,
    userVote: 0,
    comments: [],
    incognito: false,
    author: 'DeShawn R.',
    authorId: 'deshawn',
    authorVerified: true,
    createdAt: '12h ago',
    userId: 'deshawn',
    lat: 44.026,
    lng: -88.538
  },
  {
    id: '14',
    title: 'Menominee Park trails need maintenance badly',
    description: 'Fallen trees blocking paths, erosion near the lakefront, and the boardwalk has loose boards. A hazard for joggers and families.',
    category: 'parks',
    location: 'Menominee Park',
    scope: 'local',
    votes: 112,
    userVote: 0,
    comments: [],
    incognito: false,
    author: 'Natalie K.',
    authorId: 'natalie',
    authorVerified: true,
    createdAt: '1d ago',
    userId: 'natalie',
    lat: 44.018,
    lng: -88.530
  },
  {
    id: '15',
    title: 'Empty storefront on Main St — can we attract new businesses?',
    description: 'The old hardware store has been vacant for over a year. Would love to see a community co-op, bookstore, or local coffee shop move in.',
    category: 'business',
    location: 'Main St',
    scope: 'local',
    votes: 158,
    userVote: 0,
    comments: [
      { id: 'c15a', author: 'Natalie K.', authorId: 'natalie', text: 'A food co-op would be incredible there. Central location, good parking.', timestamp: Date.now() - 18000000 }
    ],
    incognito: false,
    author: 'Jamie L.',
    authorId: 'jamie',
    authorVerified: true,
    createdAt: '1d ago',
    userId: 'jamie',
    lat: 44.025,
    lng: -88.545
  },
  {
    id: '16',
    title: 'Water main break on Washington Ave flooding basements',
    description: 'Multiple homes on the 400 block have flooded basements. The city sent trucks but the leak is still going. Need emergency response.',
    category: 'other',
    location: 'Washington Ave',
    scope: 'local',
    votes: 287,
    userVote: 0,
    comments: [
      { id: 'c16a', author: 'OshkoshNative', authorId: 'oshkoshnative', text: 'This happened last spring too. The pipes on this block are ancient.', timestamp: Date.now() - 10800000 },
      { id: 'c16b', author: 'CommuteDad', authorId: 'commutedad', text: 'My neighbor lost thousands in damages. Insurance won\'t cover it.', timestamp: Date.now() - 7200000 }
    ],
    incognito: false,
    author: 'Marcus T.',
    authorId: 'marcus',
    authorVerified: true,
    createdAt: '4h ago',
    userId: 'marcus',
    lat: 44.022,
    lng: -88.547
  },
  {
    id: '17',
    title: 'GO Transit needs Sunday service',
    description: 'No buses on Sunday means no way to get to work for those without cars. This hurts service workers the most.',
    category: 'transit',
    location: 'Citywide',
    scope: 'local',
    votes: 124,
    userVote: 0,
    comments: [
      { id: 'c17a', author: 'BusRider22', authorId: 'busrider22', text: 'I have to spend $25 on Uber every Sunday just to get to my shift. That\'s $100/month.', timestamp: Date.now() - 21600000 }
    ],
    incognito: false,
    author: 'DeShawn R.',
    authorId: 'deshawn',
    authorVerified: true,
    createdAt: '2d ago',
    userId: 'deshawn',
    lat: 44.024,
    lng: -88.543
  },
  {
    id: '18',
    title: 'Landlord refuses to fix heating — 3 months and counting',
    description: 'Reported broken heating in January. It\'s still not fixed. Landlord ignores calls. Is there a tenant protection office in Oshkosh?',
    category: 'housing',
    location: 'Near UW Oshkosh',
    scope: 'local',
    votes: 96,
    userVote: 0,
    comments: [
      { id: 'c18a', author: 'Desiree W.', authorId: 'desiree', text: 'Contact the city building inspector. They can force the landlord to act.', timestamp: Date.now() - 43200000 }
    ],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '2d ago',
    userId: 'other',
    lat: 44.028,
    lng: -88.554
  },
  {
    id: '19',
    title: 'The Pollock Community Water Park is a gem',
    description: 'Took the kids this weekend and it was spotless, well-staffed, and affordable. Oshkosh gets this right.',
    category: 'compliment',
    location: 'Pollock Water Park',
    scope: 'local',
    votes: 152,
    userVote: 0,
    comments: [],
    incognito: false,
    author: 'Desiree W.',
    authorId: 'desiree',
    authorVerified: true,
    createdAt: '3d ago',
    userId: 'desiree',
    lat: 44.017,
    lng: -88.540
  },
  {
    id: '20',
    title: 'Speeding on Murdock Ave is out of control',
    description: 'People treating it like a highway. Speed bumps or radar signs are needed before someone gets killed.',
    category: 'safety',
    location: 'Murdock Ave',
    scope: 'local',
    votes: 201,
    userVote: 0,
    comments: [
      { id: 'c20a', author: 'CommuteDad', authorId: 'commutedad', text: 'Agreed. I\'ve seen people doing 50+ in a 25 zone.', timestamp: Date.now() - 36000000 }
    ],
    incognito: false,
    author: 'Marcus T.',
    authorId: 'marcus',
    authorVerified: true,
    createdAt: '3d ago',
    userId: 'marcus',
    lat: 44.019,
    lng: -88.536
  },
  {
    id: '21',
    title: 'Dog park at Fuechsl Park needs a water fountain',
    description: 'Great dog park but no water source. In summer, dogs are overheating. A simple fountain would make a huge difference.',
    category: 'parks',
    location: 'Fuechsl Park',
    scope: 'local',
    votes: 67,
    userVote: 0,
    comments: [],
    incognito: false,
    author: 'Natalie K.',
    authorId: 'natalie',
    authorVerified: true,
    createdAt: '4d ago',
    userId: 'natalie',
    lat: 44.030,
    lng: -88.550
  },
  {
    id: '22',
    title: 'New Arby\'s on Koeller — do we really need another fast food chain?',
    description: 'Would much rather see local restaurants get support. The Koeller strip is already nothing but chains.',
    category: 'business',
    location: 'Koeller St',
    scope: 'local',
    votes: 94,
    userVote: 0,
    comments: [
      { id: 'c22a', author: 'ArtLover', authorId: 'artlover', text: 'Oshkosh has amazing local food. We should be promoting that, not more chains.', timestamp: Date.now() - 50400000 }
    ],
    incognito: false,
    author: 'Jamie L.',
    authorId: 'jamie',
    authorVerified: true,
    createdAt: '4d ago',
    userId: 'jamie',
    lat: 44.016,
    lng: -88.536
  },
  {
    id: '23',
    title: 'Graffiti under the Ceape Ave bridge getting worse',
    description: 'What used to be harmless tags is now vulgar and gang-related. Needs cleanup and maybe a legal mural wall instead.',
    category: 'safety',
    location: 'Ceape Ave Bridge',
    scope: 'local',
    votes: 71,
    userVote: 0,
    comments: [],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '5d ago',
    userId: 'other',
    lat: 44.023,
    lng: -88.541
  },
  {
    id: '24',
    title: 'Library summer reading program is fantastic',
    description: 'The Oshkosh Public Library just announced their summer lineup. Free programs for kids of all ages. This community investment pays off.',
    category: 'compliment',
    location: 'Oshkosh Public Library',
    scope: 'local',
    votes: 78,
    userVote: 0,
    comments: [
      { id: 'c24a', author: 'Desiree W.', authorId: 'desiree', text: 'My kids look forward to this every year. Thank you to the library staff!', timestamp: Date.now() - 64800000 }
    ],
    incognito: false,
    author: 'Jamie L.',
    authorId: 'jamie',
    authorVerified: true,
    createdAt: '5d ago',
    userId: 'jamie',
    lat: 44.025,
    lng: -88.544
  },
  {
    id: '25',
    title: 'Pot smell from apartment complex — is this legal?',
    description: 'The hallways in my building reek constantly. Other tenants have complained but management does nothing.',
    category: 'noise',
    location: 'Near Pioneer Dr',
    scope: 'local',
    votes: 47,
    userVote: 0,
    comments: [],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '6d ago',
    userId: 'other',
    lat: 44.015,
    lng: -88.548
  },
  {
    id: '26',
    title: 'Sidewalk on High Ave is crumbling — wheelchair inaccessible',
    description: 'My mother uses a wheelchair and can\'t navigate High Ave anymore. The sidewalk is broken up and there are no curb cuts.',
    category: 'pothole',
    location: 'High Ave',
    scope: 'local',
    votes: 218,
    userVote: 0,
    comments: [
      { id: 'c26a', author: 'BusRider22', authorId: 'busrider22', text: 'ADA compliance isn\'t optional. The city needs to fix this.', timestamp: Date.now() - 72000000 }
    ],
    incognito: false,
    author: 'Desiree W.',
    authorId: 'desiree',
    authorVerified: true,
    createdAt: '6d ago',
    userId: 'desiree',
    lat: 44.026,
    lng: -88.546
  },
  {
    id: '27',
    title: 'Free little libraries popping up everywhere — love it',
    description: 'Counted 4 new little free libraries on my walk today. Neighbors sharing books is peak community.',
    category: 'compliment',
    location: 'Various neighborhoods',
    scope: 'local',
    votes: 68,
    userVote: 0,
    comments: [],
    incognito: false,
    author: 'Natalie K.',
    authorId: 'natalie',
    authorVerified: true,
    createdAt: '1w ago',
    userId: 'natalie',
    lat: 44.021,
    lng: -88.551
  },
  {
    id: '28',
    title: 'Bus route 3 discontinued — how do I get to the east side?',
    description: 'Route 3 was the only connection between west side neighborhoods and east side shopping. Now there\'s a 2-mile gap with no transit.',
    category: 'transit',
    location: 'West Side',
    scope: 'local',
    votes: 108,
    userVote: 0,
    comments: [],
    incognito: false,
    author: 'DeShawn R.',
    authorId: 'deshawn',
    authorVerified: true,
    createdAt: '1w ago',
    userId: 'deshawn',
    lat: 44.022,
    lng: -88.558
  },
  {
    id: '29',
    title: 'Wittman Airport noise has increased significantly',
    description: 'More small aircraft running early morning and late evening flights. Is EAA prep already starting? Residents near the airport are losing sleep.',
    category: 'noise',
    location: 'Near Wittman Airport',
    scope: 'local',
    votes: 68,
    userVote: 0,
    comments: [
      { id: 'c29a', author: 'OshkoshNative', authorId: 'oshkoshnative', text: 'It\'s EAA season. It\'ll only get louder from here through July.', timestamp: Date.now() - 86400000 }
    ],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '1w ago',
    userId: 'other',
    lat: 44.029,
    lng: -88.557
  },
  {
    id: '30',
    title: 'Can we get a crosstown bike trail like Appleton?',
    description: 'Appleton has a connected trail system that goes from east to west. Oshkosh has patchwork trails that dead-end. Time to invest in connectivity.',
    category: 'parks',
    location: 'Citywide',
    scope: 'local',
    votes: 121,
    userVote: 0,
    comments: [
      { id: 'c30a', author: 'DeShawn R.', authorId: 'deshawn', text: 'This would reduce traffic AND improve health outcomes. Win-win.', timestamp: Date.now() - 90000000 }
    ],
    incognito: false,
    author: 'Jamie L.',
    authorId: 'jamie',
    authorVerified: true,
    createdAt: '1w ago',
    userId: 'jamie',
    lat: 44.024,
    lng: -88.543
  },
  {
    id: '31',
    title: 'Rent increase of $200/mo with zero improvements',
    description: 'My landlord raised rent from $850 to $1050 with no upgrades. Same broken dishwasher, same stained carpet. Where do we go?',
    category: 'housing',
    location: 'South Side',
    scope: 'local',
    votes: 149,
    userVote: 0,
    comments: [],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '1w ago',
    userId: 'other',
    lat: 44.018,
    lng: -88.545
  },
  {
    id: '32',
    title: 'Oshkosh Food Co-op just opened — support local!',
    description: 'Local producers, fair prices, community-owned. This is what happens when neighbors invest in each other.',
    category: 'business',
    location: 'Downtown',
    scope: 'local',
    votes: 134,
    userVote: 0,
    comments: [
      { id: 'c32a', author: 'Natalie K.', authorId: 'natalie', text: 'Their local cheese selection is incredible. So proud of this city.', timestamp: Date.now() - 108000000 }
    ],
    incognito: false,
    author: 'Natalie K.',
    authorId: 'natalie',
    authorVerified: true,
    createdAt: '1w ago',
    userId: 'natalie',
    lat: 44.025,
    lng: -88.542
  },
  {
    id: '33',
    title: 'Flooding on Smith Ave after every heavy rain',
    description: 'Storm drains are clearly blocked or undersized. The road becomes impassable. Cars have been stranded.',
    category: 'other',
    location: 'Smith Ave',
    scope: 'local',
    votes: 143,
    userVote: 0,
    comments: [],
    incognito: false,
    author: 'Marcus T.',
    authorId: 'marcus',
    authorVerified: true,
    createdAt: '1w ago',
    userId: 'marcus',
    lat: 44.020,
    lng: -88.537
  },
  // ─── QUESTION PULSES (community decides) ─────────────────────────────────
  {
    id: 'q1',
    type: 'question',
    title: 'What color theme should the new flower beds on Main Street feature this spring?',
    description: 'Public Works has the budget approved and is asking residents to weigh in. The top-voted answer will be the consensus recommendation sent to City Hall.',
    category: 'parks',
    location: 'Main Street',
    scope: 'local',
    votes: 89,
    userVote: 0,
    comments: [
      { id: 'q1c1', author: 'Natalie K.', authorId: 'natalie', text: 'Wildflower mix — pollinator-friendly, supports our bees, low maintenance.', votes: 124, userVote: 0, timestamp: Date.now() - 72000000 },
      { id: 'q1c2', author: 'OshkoshNative', authorId: 'oshkoshnative', text: 'Blue and gold — Oshkosh colors. City pride right on Main.', votes: 47, userVote: 0, timestamp: Date.now() - 86400000 },
      { id: 'q1c3', author: 'Jamie L.', authorId: 'jamie', text: 'All white — classic, photogenic, works against any backdrop.', votes: 31, userVote: 0, timestamp: Date.now() - 50000000 },
      { id: 'q1c4', author: 'ArtLover', authorId: 'artlover', text: 'Sunset palette — orange, red, yellow. Stands out from a block away.', votes: 18, userVote: 0, timestamp: Date.now() - 40000000 }
    ],
    incognito: false,
    author: 'Jamie L.',
    authorId: 'jamie',
    authorVerified: true,
    createdAt: '2d ago',
    createdAtTs: Date.now() - 172800000,
    userId: 'jamie',
    lat: 44.025,
    lng: -88.544
  },
  {
    id: 'q2',
    type: 'question',
    title: 'What should we name the new pocket park opening on 9th Ave?',
    description: 'The new park between Oregon and Jackson opens this fall. The Parks Department is taking community submissions for the name.',
    category: 'parks',
    location: '9th Ave',
    scope: 'local',
    votes: 134,
    userVote: 0,
    comments: [
      { id: 'q2c1', author: 'Desiree W.', authorId: 'desiree', text: 'Marian Memorial Park — name it after Marian Schultz, the neighborhood advocate who passed last year. She fought for this lot for twenty years.', votes: 178, userVote: 0, timestamp: Date.now() - 90000000 },
      { id: 'q2c2', author: 'Marcus T.', authorId: 'marcus', text: 'Lakeside Commons — simple, evergreen, ties to the city identity.', votes: 56, userVote: 0, timestamp: Date.now() - 100000000 },
      { id: 'q2c3', author: 'OshkoshNative', authorId: 'oshkoshnative', text: 'Founders Green — honors the city heritage without picking one name.', votes: 42, userVote: 0, timestamp: Date.now() - 80000000 },
      { id: 'q2c4', author: 'CommuteDad', authorId: 'commutedad', text: 'Just call it 9th Avenue Park. Easy to find, easy to remember.', votes: 21, userVote: 0, timestamp: Date.now() - 70000000 }
    ],
    incognito: false,
    author: 'Marcus T.',
    authorId: 'marcus',
    authorVerified: true,
    createdAt: '3d ago',
    createdAtTs: Date.now() - 259200000,
    userId: 'marcus',
    lat: 44.024,
    lng: -88.541
  },
  {
    id: 'q3',
    type: 'question',
    title: 'Where should the next dog park be built — north side or south side?',
    description: 'Fuechsl is consistently overcrowded. Parks Dept has funding for one new dog park and is asking residents which neighborhood needs it most.',
    category: 'parks',
    location: 'Citywide',
    scope: 'local',
    votes: 102,
    userVote: 0,
    comments: [
      { id: 'q3c1', author: 'DeShawn R.', authorId: 'deshawn', text: 'North side — Fuechsl already covers the center and south. Nothing exists past Murdock.', votes: 87, userVote: 0, timestamp: Date.now() - 60000000 },
      { id: 'q3c2', author: 'Desiree W.', authorId: 'desiree', text: 'South side — closer to the highest-density apartments where dog owners actually live.', votes: 64, userVote: 0, timestamp: Date.now() - 50000000 },
      { id: 'q3c3', author: 'Natalie K.', authorId: 'natalie', text: 'Honestly both. Fuechsl is unusable on weekends. We need at least one more, period.', votes: 39, userVote: 0, timestamp: Date.now() - 40000000 }
    ],
    incognito: false,
    author: 'Desiree W.',
    authorId: 'desiree',
    authorVerified: true,
    createdAt: '4d ago',
    createdAtTs: Date.now() - 345600000,
    userId: 'desiree',
    lat: 44.024,
    lng: -88.544
  },
  {
    id: 'q5',
    type: 'question',
    title: "What's the best pizza in Oshkosh?",
    description: 'Settling this once and for all. Drop your pick in the answers — the top-voted reply becomes the community Verdict.',
    category: 'business',
    location: 'Oshkosh',
    scope: 'local',
    votes: 218,
    userVote: 0,
    comments: [
      { id: 'q5c1', author: 'OshkoshNative', authorId: 'oshkoshnative', text: "Dr. Benzies. If you know, you know — and if you don't, the line out the door on a Friday should tell you.", votes: 287, userVote: 0, timestamp: Date.now() - 120000000 },
      { id: 'q5c2', author: 'Marcus T.', authorId: 'marcus', text: "Polito's after 11pm. Different rules apply.", votes: 156, userVote: 0, timestamp: Date.now() - 80000000 },
      { id: 'q5c3', author: 'CommuteDad', authorId: 'commutedad', text: "Mark's East Side. It's a bar, sure, but the pizza is what brings me back.", votes: 121, userVote: 0, timestamp: Date.now() - 95000000 },
      { id: 'q5c4', author: 'Jamie L.', authorId: 'jamie', text: "Dr. Benzies for the pie itself, Polito's for late night, Mark's for a beer with it. Best pizza is contextual.", votes: 142, userVote: 0, timestamp: Date.now() - 55000000 },
      { id: 'q5c5', author: 'BusRider22', authorId: 'busrider22', text: 'Honestly, Benzies hasn\'t missed in years. Hard to argue with consistency.', votes: 98, userVote: 0, timestamp: Date.now() - 70000000 },
      { id: 'q5c6', author: 'ArtLover', authorId: 'artlover', text: "Hot take: Polito's is fine but it's the bar food of pizza. Benzies is the actual pizza.", votes: 73, userVote: 0, timestamp: Date.now() - 60000000 }
    ],
    incognito: false,
    author: 'Marcus T.',
    authorId: 'marcus',
    authorVerified: true,
    createdAt: '6d ago',
    createdAtTs: Date.now() - 518400000,
    userId: 'marcus',
    lat: 44.024,
    lng: -88.543
  },
  {
    id: 'q4',
    type: 'question',
    title: 'Should the downtown farmers market stay on Saturdays or move to Sunday mornings?',
    description: 'Vendors are split. Saturday traffic competes with downtown events; Sunday opens family time. The market board is putting it to the community.',
    category: 'business',
    location: 'Downtown Oshkosh',
    scope: 'local',
    votes: 76,
    userVote: 0,
    comments: [
      { id: 'q4c1', author: 'Natalie K.', authorId: 'natalie', text: 'Keep Saturday. Foot traffic from downtown events is what makes the market what it is.', votes: 92, userVote: 0, timestamp: Date.now() - 30000000 },
      { id: 'q4c2', author: 'CommuteDad', authorId: 'commutedad', text: 'Move to Sunday. Saturday mornings are already overcommitted for most families.', votes: 38, userVote: 0, timestamp: Date.now() - 25000000 },
      { id: 'q4c3', author: 'BusRider22', authorId: 'busrider22', text: 'Run it both days during peak season. Vendors win, residents win.', votes: 54, userVote: 0, timestamp: Date.now() - 20000000 }
    ],
    incognito: false,
    author: 'Natalie K.',
    authorId: 'natalie',
    authorVerified: true,
    createdAt: '5d ago',
    createdAtTs: Date.now() - 432000000,
    userId: 'natalie',
    lat: 44.025,
    lng: -88.543
  }
]

export const STATE_SEED_POSTS = [
  {
    id: 's1',
    title: 'Wisconsin public school funding is falling behind neighboring states',
    description: 'Per-pupil spending in WI has dropped relative to Minnesota and Illinois over the past decade. Our kids deserve competitive investment in their education.',
    category: 'education',
    location: 'Statewide',
    scope: 'state',
    votes: 1247,
    userVote: 0,
    comments: [
      { id: 'sc1', author: 'Marcus T.', authorId: 'marcus', text: 'Oshkosh schools have been asking for operating referendum after referendum. The state formula needs to change.', timestamp: Date.now() - 7200000 },
      { id: 'sc2', author: 'Jamie L.', authorId: 'jamie', text: 'As a teacher, I see this every day. We\'re losing good educators to states that pay more.', timestamp: Date.now() - 3600000 }
    ],
    incognito: false,
    author: 'Marcus T.',
    authorId: 'marcus',
    authorVerified: true,
    createdAt: '6h ago',
    userId: 'marcus',
    lat: null,
    lng: null
  },
  {
    id: 's2',
    title: 'Expand Medicaid coverage to close the insurance gap',
    description: 'Over 90,000 Wisconsinites fall in the coverage gap. Expanding BadgerCare would bring billions in federal funding back to our state.',
    category: 'healthcare',
    location: 'Statewide',
    scope: 'state',
    votes: 934,
    userVote: 0,
    comments: [
      { id: 'sc3', author: 'Desiree W.', authorId: 'desiree', text: 'I know families who have to choose between groceries and prescriptions. This shouldn\'t happen in Wisconsin.', timestamp: Date.now() - 14400000 }
    ],
    incognito: false,
    author: 'Desiree W.',
    authorId: 'desiree',
    authorVerified: true,
    createdAt: '1d ago',
    userId: 'desiree',
    lat: null,
    lng: null
  },
  {
    id: 's3',
    title: 'I-43 corridor desperately needs modernization',
    description: 'The I-43 corridor between Milwaukee and Green Bay is one of the deadliest stretches in the state. Widening and safety upgrades are long overdue.',
    category: 'infrastructure',
    location: 'I-43 Corridor',
    scope: 'state',
    votes: 672,
    userVote: 0,
    comments: [],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '2d ago',
    userId: 'other',
    lat: null,
    lng: null
  },
  {
    id: 's4',
    title: 'PFAS contamination in drinking water — where is the state action?',
    description: 'Multiple communities across Wisconsin have detected PFAS "forever chemicals" in their water supply. We need statewide standards and cleanup funding now.',
    category: 'environment',
    location: 'Multiple Counties',
    scope: 'state',
    votes: 1089,
    userVote: 0,
    comments: [
      { id: 'sc4', author: 'OshkoshNative', authorId: 'oshkoshnative', text: 'This is a public health emergency. Marinette, La Crosse, and now Oshkosh — how many more communities?', timestamp: Date.now() - 28800000 }
    ],
    incognito: false,
    author: 'Natalie K.',
    authorId: 'natalie',
    authorVerified: true,
    createdAt: '3d ago',
    userId: 'natalie',
    lat: null,
    lng: null
  },
  {
    id: 's5',
    title: 'State budget surplus should go back to taxpayers and roads',
    description: 'Wisconsin is sitting on a $4B+ surplus. Let\'s invest it in crumbling infrastructure and provide tax relief instead of letting it sit in Madison.',
    category: 'state-budget',
    location: 'Madison, WI',
    scope: 'state',
    votes: 856,
    userVote: 0,
    comments: [
      { id: 'sc5', author: 'CommuteDad', authorId: 'commutedad', text: 'Our local roads are falling apart while the state hoards cash. Makes no sense.', timestamp: Date.now() - 36000000 }
    ],
    incognito: false,
    author: 'DeShawn R.',
    authorId: 'deshawn',
    authorVerified: true,
    createdAt: '4d ago',
    userId: 'deshawn',
    lat: null,
    lng: null
  },
  {
    id: 's6',
    title: 'Support the bipartisan redistricting reform bill',
    description: 'Fair maps mean fair representation. The nonpartisan redistricting commission bill has bipartisan support — let\'s get it passed.',
    category: 'legislation',
    location: 'Madison, WI',
    scope: 'state',
    votes: 743,
    userVote: 0,
    comments: [],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '5d ago',
    userId: 'other',
    lat: null,
    lng: null
  },
  {
    id: 's7',
    title: 'Make Election Day a state holiday for all workers',
    description: 'Voter turnout suffers when people can\'t get time off. Making Election Day a state holiday would strengthen our democracy.',
    category: 'elections',
    location: 'Statewide',
    scope: 'state',
    votes: 612,
    userVote: 0,
    comments: [
      { id: 'sc6', author: 'BusRider22', authorId: 'busrider22', text: 'I had to choose between missing a shift and voting last cycle. That\'s not right.', timestamp: Date.now() - 43200000 }
    ],
    incognito: false,
    author: 'Jamie L.',
    authorId: 'jamie',
    authorVerified: true,
    createdAt: '6d ago',
    userId: 'jamie',
    lat: null,
    lng: null
  },
  {
    id: 's8',
    title: 'Statewide rent stabilization — do we need it?',
    description: 'Wisconsin currently bans cities from implementing rent control. With rents surging in Madison, Milwaukee, and college towns, should the state allow local rent stabilization measures?',
    category: 'housing-policy',
    location: 'Statewide',
    scope: 'state',
    votes: 489,
    userVote: 0,
    comments: [],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '1w ago',
    userId: 'other',
    lat: null,
    lng: null
  },
  {
    id: 's9',
    title: 'Rural broadband is a crisis — half of northern WI has no reliable internet',
    description: 'Students can\'t do homework, businesses can\'t operate, telehealth is impossible. The state needs to treat broadband like a utility.',
    category: 'infrastructure',
    location: 'Northern Wisconsin',
    scope: 'state',
    votes: 891,
    userVote: 0,
    comments: [
      { id: 'sc9a', author: 'Marcus T.', authorId: 'marcus', text: 'My cousins in Wausau have to drive to McDonald\'s parking lot for wifi. In 2026.', timestamp: Date.now() - 14400000 }
    ],
    incognito: false,
    author: 'DeShawn R.',
    authorId: 'deshawn',
    authorVerified: true,
    createdAt: '2d ago',
    userId: 'deshawn',
    lat: null,
    lng: null
  },
  {
    id: 's10',
    title: 'Childcare costs are forcing parents out of the workforce',
    description: 'Average childcare in WI costs $12,000+/year per child. Many parents — especially mothers — are leaving jobs because it\'s cheaper to stay home.',
    category: 'state-budget',
    location: 'Statewide',
    scope: 'state',
    votes: 1102,
    userVote: 0,
    comments: [
      { id: 'sc10a', author: 'Desiree W.', authorId: 'desiree', text: 'I pay more for childcare than my mortgage. Something has to give.', timestamp: Date.now() - 28800000 }
    ],
    incognito: false,
    author: 'Desiree W.',
    authorId: 'desiree',
    authorVerified: true,
    createdAt: '3d ago',
    userId: 'desiree',
    lat: null,
    lng: null
  },
  {
    id: 's11',
    title: 'Universal background checks for gun purchases — where does WI stand?',
    description: 'Wisconsin has no universal background check requirement for private sales. With gun violence rising, should we close this loophole?',
    category: 'legislation',
    location: 'Statewide',
    scope: 'state',
    votes: 567,
    userVote: 0,
    comments: [],
    incognito: true,
    author: null,
    authorId: null,
    authorVerified: true,
    createdAt: '4d ago',
    userId: 'other',
    lat: null,
    lng: null
  },
  {
    id: 's12',
    title: 'Protect the Great Lakes from Line 5 pipeline risks',
    description: 'The Enbridge Line 5 pipeline under the Straits of Mackinac threatens the entire Great Lakes ecosystem. Wisconsin should join Michigan in demanding safety upgrades.',
    category: 'environment',
    location: 'Lake Michigan',
    scope: 'state',
    votes: 783,
    userVote: 0,
    comments: [
      { id: 'sc12a', author: 'Natalie K.', authorId: 'natalie', text: 'Lake Michigan provides drinking water for millions. This should be non-negotiable.', timestamp: Date.now() - 50400000 }
    ],
    incognito: false,
    author: 'Natalie K.',
    authorId: 'natalie',
    authorVerified: true,
    createdAt: '5d ago',
    userId: 'natalie',
    lat: null,
    lng: null
  },
  {
    id: 's13',
    title: 'Wisconsin is losing skilled trades workers at an alarming rate',
    description: 'Plumbers, electricians, and welders are retiring faster than we can replace them. The state needs to invest in technical college funding and apprenticeship programs.',
    category: 'education',
    location: 'Statewide',
    scope: 'state',
    votes: 645,
    userVote: 0,
    comments: [
      { id: 'sc13a', author: 'CommuteDad', authorId: 'commutedad', text: 'My plumber is booked 6 weeks out. We need to make trades attractive to young people again.', timestamp: Date.now() - 64800000 }
    ],
    incognito: false,
    author: 'Marcus T.',
    authorId: 'marcus',
    authorVerified: true,
    createdAt: '5d ago',
    userId: 'marcus',
    lat: null,
    lng: null
  },
  {
    id: 's14',
    title: 'Legalize and tax recreational cannabis — WI is surrounded',
    description: 'Illinois, Michigan, and Minnesota all have legal cannabis. Wisconsin residents are driving across state lines and WI is missing out on hundreds of millions in tax revenue.',
    category: 'legislation',
    location: 'Statewide',
    scope: 'state',
    votes: 1389,
    userVote: 0,
    comments: [
      { id: 'sc14a', author: 'BusRider22', authorId: 'busrider22', text: 'Illinois made $1.5 BILLION in cannabis revenue last year. That money could fix our roads.', timestamp: Date.now() - 72000000 },
      { id: 'sc14b', author: 'ArtLover', authorId: 'artlover', text: 'The border dispensaries in Illinois are packed with WI plates. The revenue is already leaving the state.', timestamp: Date.now() - 43200000 }
    ],
    incognito: false,
    author: 'Jamie L.',
    authorId: 'jamie',
    authorVerified: true,
    createdAt: '6d ago',
    userId: 'jamie',
    lat: null,
    lng: null
  },
  {
    id: 's15',
    title: 'Lead pipe replacement — 400,000 homes still at risk',
    description: 'Wisconsin has one of the highest concentrations of lead service lines in the nation. Federal funding exists but the state needs to streamline the replacement process.',
    category: 'healthcare',
    location: 'Statewide',
    scope: 'state',
    votes: 712,
    userVote: 0,
    comments: [],
    incognito: false,
    author: 'Desiree W.',
    authorId: 'desiree',
    authorVerified: true,
    createdAt: '1w ago',
    userId: 'desiree',
    lat: null,
    lng: null
  },
  {
    id: 's16',
    title: 'Mental health crisis: WI ranks 34th in access to care',
    description: 'Long wait times, shortage of providers, and stigma. Rural areas have almost no access. We need state-funded crisis centers and telehealth expansion.',
    category: 'healthcare',
    location: 'Statewide',
    scope: 'state',
    votes: 834,
    userVote: 0,
    comments: [
      { id: 'sc16a', author: 'Jamie L.', authorId: 'jamie', text: 'As a teacher I see kids struggling with no resources. The waitlist for a school psychologist is 6 months.', timestamp: Date.now() - 86400000 }
    ],
    incognito: false,
    author: 'Jamie L.',
    authorId: 'jamie',
    authorVerified: true,
    createdAt: '1w ago',
    userId: 'jamie',
    lat: null,
    lng: null
  },
  {
    id: 's17',
    title: 'Property tax freeze for seniors on fixed incomes',
    description: 'Seniors who\'ve lived in their homes for 30+ years are being taxed out. A freeze for residents over 65 earning under $50K would provide real relief.',
    category: 'state-budget',
    location: 'Statewide',
    scope: 'state',
    votes: 923,
    userVote: 0,
    comments: [
      { id: 'sc17a', author: 'OshkoshNative', authorId: 'oshkoshnative', text: 'My neighbor is 78 and might lose her home because of tax increases. She\'s lived there 40 years.', timestamp: Date.now() - 100800000 }
    ],
    incognito: false,
    author: 'Marcus T.',
    authorId: 'marcus',
    authorVerified: true,
    createdAt: '1w ago',
    userId: 'marcus',
    lat: null,
    lng: null
  },
  {
    id: 's18',
    title: 'Support Wisconsin dairy farmers — the backbone of our economy',
    description: 'Family dairy farms are closing at record rates. The state should invest in value-added processing, export markets, and farm succession planning.',
    category: 'other-state',
    location: 'Statewide',
    scope: 'state',
    votes: 576,
    userVote: 0,
    comments: [],
    incognito: false,
    author: 'Natalie K.',
    authorId: 'natalie',
    authorVerified: true,
    createdAt: '2w ago',
    userId: 'natalie',
    lat: null,
    lng: null
  },
  // ─── STATE QUESTION PULSES (Wisconsin community decides) ─────────────────
  {
    id: 'sq1',
    type: 'question',
    title: 'Which state-owned forest deserves the next major trail investment?',
    description: 'The WI DNR has $3M earmarked for trail upgrades. Asking residents statewide which property would deliver the most use and economic return.',
    category: 'environment',
    location: 'Statewide',
    scope: 'state',
    votes: 412,
    userVote: 0,
    comments: [
      { id: 'sq1c1', author: 'Natalie K.', authorId: 'natalie', text: 'Northern Highland — those trails are the heart of the Northwoods tourism economy and they\'re falling apart.', votes: 218, userVote: 0, timestamp: Date.now() - 70000000 },
      { id: 'sq1c2', author: 'Marcus T.', authorId: 'marcus', text: 'Kettle Moraine — it absorbs the most volume from Milwaukee and Madison. Biggest ROI per dollar.', votes: 134, userVote: 0, timestamp: Date.now() - 80000000 },
      { id: 'sq1c3', author: 'OshkoshNative', authorId: 'oshkoshnative', text: 'Black River — the most underfunded and underused. Invest where the gap is biggest.', votes: 67, userVote: 0, timestamp: Date.now() - 60000000 },
      { id: 'sq1c4', author: 'DeShawn R.', authorId: 'deshawn', text: 'Point Beach — it serves the entire eastern shore. Trails there are basically gravel.', votes: 41, userVote: 0, timestamp: Date.now() - 55000000 }
    ],
    incognito: false,
    author: 'Natalie K.',
    authorId: 'natalie',
    authorVerified: true,
    createdAt: '5d ago',
    createdAtTs: Date.now() - 432000000,
    userId: 'natalie',
    lat: null,
    lng: null
  },
  {
    id: 'sq2',
    type: 'question',
    title: 'What should Wisconsin\'s next state license plate design feature?',
    description: 'The DOT is refreshing the standard plate for 2027. Residents are being asked what should represent the state on every car on the road.',
    category: 'other-state',
    location: 'Statewide',
    scope: 'state',
    votes: 287,
    userVote: 0,
    comments: [
      { id: 'sq2c1', author: 'Jamie L.', authorId: 'jamie', text: 'The Driftless Area landscape — most distinct geography we have, and nothing else has it.', votes: 156, userVote: 0, timestamp: Date.now() - 50000000 },
      { id: 'sq2c2', author: 'CommuteDad', authorId: 'commutedad', text: 'A simple modern badger silhouette. Clean, iconic, doesn\'t go out of style.', votes: 198, userVote: 0, timestamp: Date.now() - 45000000 },
      { id: 'sq2c3', author: 'BusRider22', authorId: 'busrider22', text: 'Lake Michigan shoreline. The Great Lakes are the most important resource we have.', votes: 87, userVote: 0, timestamp: Date.now() - 40000000 }
    ],
    incognito: false,
    author: 'Jamie L.',
    authorId: 'jamie',
    authorVerified: true,
    createdAt: '6d ago',
    createdAtTs: Date.now() - 518400000,
    userId: 'jamie',
    lat: null,
    lng: null
  }
]
